### ISSUE TITLE
How to retrieve user's name?

### ISSUE THREAD

**Issue by jinsankim** [OneDrive/onedrive-sdk-android#101]
I want to display user's name (display name, email address, or any string representing the user.).
Can I get user's name via onedrive-sdk after login success? and How?

Thanks in advance,

**Comment by jinsankim** [comment]
I found that my question is duplicated with https://github.com/OneDrive/onedrive-sdk-android/issues/35. So I'll close my issue. 

Thanks,

**Comment by peternied** [comment]
Thanks for the question @JinsanKim, - This functionality is available through the Microsoft Graph API and won’t be coming to the OneDrive API. See https://graph.microsoft.io for more details.
