### ISSUE TITLE
Synchronous login method Client loginAndBuildClient(Activity) fails

### ISSUE THREAD

**Issue by wooseopkim** [OneDrive/onedrive-sdk-android#102]
When I tried the [example](https://github.com/OneDrive/onedrive-explorer-android) it worked. But the SDK didn't work with my own code. I found that problem was the difference between the asynchronous `void loginAndBuildClient(Activity, Handler)` and synchronous `Client loginAndBuildClient(Activity)`.

Logcat was as following:

> 09-15 16:35:08.515 28362-28414/punch.steamship.ubimusique I/LiveAuthClient: No refresh token available, sorry!
> 09-15 16:35:08.515 28362-28414/punch.steamship.ubimusique I/LiveAuthClient: All tokens expired, you need to call login() to initiate interactive logon
> 09-15 16:35:08.523 28362-28414/punch.steamship.ubimusique E/MSAAuthenticator$5[onAuthComplete] - 314: Failed silent login, interactive login required
>                                                                                                       com.onedrive.sdk.authentication.ClientAuthenticatorException: Failed silent login, interactive login required
>                                                                                                           at com.onedrive.sdk.authentication.MSAAuthenticator$5.onAuthComplete(MSAAuthenticator.java:312)
>                                                                                                           at com.microsoft.services.msa.LiveAuthClient$3.doInBackground(LiveAuthClient.java:484)
>                                                                                                           at com.microsoft.services.msa.LiveAuthClient$3.doInBackground(LiveAuthClient.java:473)
>                                                                                                           at android.os.AsyncTask$2.call(AsyncTask.java:295)
>                                                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                                                                           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
>                                                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>                                                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>                                                                                                           at java.lang.Thread.run(Thread.java:818)
> 09-15 16:35:08.524 28362-28415/punch.steamship.ubimusique I/LiveAuthClient: No refresh token available, sorry!
> 09-15 16:35:08.524 28362-28415/punch.steamship.ubimusique I/LiveAuthClient: All tokens expired, you need to call login() to initiate interactive logon

If I first sign in with my account using asynchronous `loginAndBuildClient()`, then the synchronous one works. It seems to only occur if I try my first login with synchronous `loginAndBuildClient()`.

My device is Google Nexus 5, and I'm using version 24 for compileSdk, 24.0.1 for buildTools, 24 for targetSdk. Please let me know if you need any further information. Thank you.

**Comment by peternied** [comment]
Was there any additional logcat output after what you've pasted into this issue? From what I see there, no interactive login was attempted, only the silent authentication flow.

**Comment by wooseopkim** [comment]
@peternied This is all I have:

> 09-15 16:35:07.825 28362-28362/punch.steamship.ubimusique W/System: ClassLoader referenced unknown path: /data/app/punch.steamship.ubimusique-2/lib/arm
> 09-15 16:35:08.051 28362-28362/punch.steamship.ubimusique W/System: ClassLoader referenced unknown path: /data/app/punch.steamship.ubimusique-2/lib/arm
> 09-15 16:35:08.284 28362-28362/punch.steamship.ubimusique W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
> 09-15 16:35:08.515 28362-28414/punch.steamship.ubimusique I/LiveAuthClient: No refresh token available, sorry!
> 09-15 16:35:08.515 28362-28414/punch.steamship.ubimusique I/LiveAuthClient: All tokens expired, you need to call login() to initiate interactive logon
> 09-15 16:35:08.523 28362-28414/punch.steamship.ubimusique E/MSAAuthenticator$5[onAuthComplete] - 314: Failed silent login, interactive login required
>                                                                                                       com.onedrive.sdk.authentication.ClientAuthenticatorException: Failed silent login, interactive login required
>                                                                                                           at com.onedrive.sdk.authentication.MSAAuthenticator$5.onAuthComplete(MSAAuthenticator.java:312)
>                                                                                                           at com.microsoft.services.msa.LiveAuthClient$3.doInBackground(LiveAuthClient.java:484)
>                                                                                                           at com.microsoft.services.msa.LiveAuthClient$3.doInBackground(LiveAuthClient.java:473)
>                                                                                                           at android.os.AsyncTask$2.call(AsyncTask.java:295)
>                                                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                                                                           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
>                                                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>                                                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>                                                                                                           at java.lang.Thread.run(Thread.java:818)
> 09-15 16:35:08.524 28362-28415/punch.steamship.ubimusique I/LiveAuthClient: No refresh token available, sorry!
> 09-15 16:35:08.524 28362-28415/punch.steamship.ubimusique I/LiveAuthClient: All tokens expired, you need to call login() to initiate interactive logon
> 09-15 16:35:08.529 28362-28362/punch.steamship.ubimusique I/WebViewFactory: Loading com.google.android.webview version 52.0.2743.98 (code 275609800)
> 09-15 16:35:08.565 28362-28362/punch.steamship.ubimusique I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
> 09-15 16:35:08.565 28362-28362/punch.steamship.ubimusique I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
> 09-15 16:35:08.567 28362-28362/punch.steamship.ubimusique I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
> 09-15 16:35:08.567 28362-28362/punch.steamship.ubimusique I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
> 09-15 16:35:08.574 28362-28362/punch.steamship.ubimusique I/cr_LibraryLoader: Time to load native libraries: 1 ms (timestamps 1166-1167)
> 09-15 16:35:08.574 28362-28362/punch.steamship.ubimusique I/cr_LibraryLoader: Expected native library version number "52.0.2743.98", actual native library version number "52.0.2743.98"
> 09-15 16:35:08.589 28362-28362/punch.steamship.ubimusique V/WebViewChromiumFactoryProvider: Binding Chromium to main looper Looper (main, tid 1) {9f426e5}
> 09-15 16:35:08.589 28362-28362/punch.steamship.ubimusique I/cr_LibraryLoader: Expected native library version number "52.0.2743.98", actual native library version number "52.0.2743.98"
> 09-15 16:35:08.589 28362-28362/punch.steamship.ubimusique I/chromium: [INFO:library_loader_hooks.cc(143)] Chromium logging enabled: level = 0, default verbosity = 0
> 09-15 16:35:08.596 28362-28362/punch.steamship.ubimusique I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
> 09-15 16:35:08.613 28362-28362/punch.steamship.ubimusique I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
> 09-15 16:35:08.664 28362-28426/punch.steamship.ubimusique W/cr_media: Requires BLUETOOTH permission
> 09-15 16:35:08.711 28362-28362/punch.steamship.ubimusique W/cr_AwContents: onDetachedFromWindow called when already detached. Ignoring
> 09-15 16:35:08.720 28362-28362/punch.steamship.ubimusique I/cr_Ime: ImeThread is not enabled.
> 09-15 16:35:08.740 28362-28434/punch.steamship.ubimusique D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
> 09-15 16:35:08.784 28362-28438/punch.steamship.ubimusique E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
> 09-15 16:35:08.810 28362-28438/punch.steamship.ubimusique W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
> 09-15 16:35:08.835 28362-28438/punch.steamship.ubimusique I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es

And the (Kotlin) code is:

``` kotlin
    // companion object fields: equivalent of static variables
    private val AUTH = object: MSAAuthenticator() {
        override fun getClientId() = CLIENT_ID
        override fun getScopes() = SCOPES
    }
    private val CONFIG = DefaultClientConfig.createWithAuthenticator(AUTH)
```

``` kotlin
    private val activity: Activity
    private val client: IOneDriveClient

    constructor(context: Activity) {
        this.activity = context
        client = OneDriveClient.Builder()
                .fromConfig(CONFIG)
                .loginAndBuildClient(activity)
    }
```

**Comment by peternied** [comment]
Thanks for the additional detail we will look into this.

**Comment by daboxu** [comment]
@linterpreteur it seems it is related to the issue #49, going to merge this to the main thread.

**Comment by wooseopkim** [comment]
Ok, thank you.

**Comment by daboxu** [comment]
@linterpreteur the fix #103 hides the synchronous build OneDrive client because it causes deadlock if you invoke it directly from UI thread. Please use the callback versions.

**Comment by wooseopkim** [comment]
Thanks a lot.

**Comment by mvysny** [comment]
The README.md at the main page ( https://github.com/OneDrive/onedrive-sdk-android ) still uses the synchronous method as a primary example; this will simply freeze the application when an initial login is needed.

**Comment by daboxu** [comment]
@mvysny thanks for notice, the doc is updated now!
