### ISSUE TITLE
The synchronous post request for copying returned before the file is actually copied.

### ISSUE THREAD

**Issue by jinsankim** [OneDrive/onedrive-sdk-android#106]
Hi,

I wrote the below code for copying a file using synchronous post request.

`
final ItemReference parentReference = new ItemReference();
parentReference.path = getOneDrivePath(dst.getParentPath());

mClient.get().getDrive()
                    .getItems(src.getFileId())
                    .getCopy(dst.getFileName(), parentReference)
                    .buildRequest()
                    .post();
`

After the post returned, I request the item copied just now. But the item doesn't exist. So I tried to request the item in a loop (polling) then I can get the copied item through several times tries. I thinks post should be returned after the copied item is available.

Any idea?

**Comment by peternied** [comment]
The result of the copy is not the copied item, but an asynchronous monitor that can be polled for when a copy action has completed. 

See the detailed [copy documentation](https://github.com/OneDrive/onedrive-sdk-android/blob/master/docs/items.md#copy-an-item).  In the [OneDrive Explorer for Android](https://github.com/OneDrive/onedrive-explorer-android), there is also a [full example](https://github.com/OneDrive/onedrive-explorer-android/blob/master/app/src/main/java/com/microsoft/onedrive/apiexplorer/ItemFragment.java#L325) of how the copy system works.

**Comment by jinsankim** [comment]
@peternied Thanks a lot. 👍

**Comment by peternied** [comment]
I'm going to close out this question since you have got the answers you need, if not please reopen.  If you happen to have any other questions/comments open up a new issue.
