### ISSUE TITLE
MSA autentification screen.

### ISSUE THREAD

**Issue by isabsent** [OneDrive/onedrive-sdk-android#110]
To avoid a bug in the authentication for API < 18 (#109), ADAL authentication was turned off and [MSA authentication dialog](https://cloud.githubusercontent.com/assets/4918293/19880843/3d325160-a033-11e6-9666-6233b4d4c607.png) appears. It is little bit messy - not centered and has transparent areas that leads to partial background activity visibility. Is it possible to fix this mistakes?

P.S. This bug is visible on Android emulator API 16 (with Google APIs) and probably this is an emulator problem...

**Comment by daboxu** [comment]
what screen size & solution for your emulator? I used nexus 4 (7'' 768x1280 xhdpi) as my emulator seems work for me, curious it could happened for smaller screen. 
![capture screen](https://cloud.githubusercontent.com/assets/3971919/20536004/213ca6e4-b09c-11e6-9874-a29c29f020f3.PNG)

**Comment by isabsent** [comment]
Nevermind! It was an x86 emulator with API 16 for Nexus 5x problem as I suppose.

**Comment by daboxu** [comment]
cool
