### ISSUE TITLE
InstantRun fails with class signature mismatch

### ISSUE THREAD

**Issue by Mdany** [OneDrive/onedrive-sdk-android#113]
Same exception.I workaround and can't use instant run.
Maybe you need to track the problem 
😊
 
https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/724

**Comment by daboxu** [comment]
thanks!

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
