### ISSUE TITLE
Account ID

### ISSUE THREAD

**Issue by cmakthat** [OneDrive/onedrive-sdk-android#114]
Does the OneDrive Android SDK have an equivalent to the "Account ID" found in iOS and Windows 10 SDKs? These aren't the actual emails of the users but a unique identifier returned after OAuth occurs according to the documentation:

Values for access_token, authentication_token, and user_id are truncated in the previous example. 

Using the endpoint "https://apis.live.net/v5.0/me?access_token=" gives an entirely different id than the ones found during the OAuth.

<img width="782" alt="screen shot 2016-11-22 at 3 30 06 pm" src="https://cloud.githubusercontent.com/assets/4925735/20546275/fce454cc-b0c8-11e6-9ce8-8fd1ac96190d.png">

<img width="862" alt="screen shot 2016-11-22 at 3 30 16 pm" src="https://cloud.githubusercontent.com/assets/4925735/20546281/00d0c390-b0c9-11e6-8ae2-f5f4a35f44d9.png">

**Comment by daboxu** [comment]
@cmakthat unfortunately the Android version doesn't support it yet as it relies on the OauthResponse in the package msa-auth package: https://github.com/OfficeDev/msa-auth-for-android/blob/master/src/main/java/com/microsoft/services/msa/OAuthSuccessfulResponse.java

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
