### ISSUE TITLE
Original exception ignored in DisambiguationAuthenticator failure callback

### ISSUE THREAD

**Issue by mdobric** [OneDrive/onedrive-sdk-android#116]
The failure callback in DisambiguationAuthenticator.login(String), line 187, replaces the original exception with a new one. This is a problem when trying to figure out why disambiguation failed. Currently it's impossible to tell whether the user pressed the back button or if something else went wrong. Please pass along the original exception when constructing the new one.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
