### ISSUE TITLE
getNextPage() is always null for synchronous call.

### ISSUE THREAD

**Issue by isabsent** [OneDrive/onedrive-sdk-android#117]
I am making synchronous call (using get() without callback in the argument in a non-UI thread):

    Item loadedItem = oneDriveClient
        .getDrive()
        .getItems(item.id)
        .buildRequest()
        .expand(getExpansionOptions(service))
        .get();

    List<Item> currentPageList = loadedItem.children.getCurrentPage();
    int currentPageSize = currentPageList.size();
    boolean hasNextPage = loadedItem.children.getNextPage() != null;
to the folder containing more than 200 files. The result is:

    currentPageSize = 200;
    hasNextPage = false
Should hasNextPage be true for synchronous call if folder contains more than 200 files?
P.S.:

    private String getExpansionOptions(final IOneDriveClient oneDriveClient) {
        final String expansionOption;
        switch (oneDriveClient.getAuthenticator().getAccountInfo().getAccountType()) {
            case MicrosoftAccount:
                expansionOption = EXPAND_OPTIONS_FOR_CHILDREN_AND_THUMBNAILS;
                break;

            default:
                expansionOption = EXPAND_OPTIONS_FOR_CHILDREN_AND_THUMBNAILS_LIMITED;
                break;
        }
        return expansionOption;
    }

**Comment by isabsent** [comment]
Hi, guys! Did you check this issue!? It make impossible to list files in a huge folder!

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
