### ISSUE TITLE
Distribute as onedrive-sdk-android.jar

### ISSUE THREAD

**Issue by isabsent** [OneDrive/onedrive-sdk-android#12]
Your library does not contain resources. Therefore it may be distributed as simple jar archive. It would be useful for those who do not use Gradle or Maven.

**Comment by peternied** [comment]
This SDK depends on getting permissions to account management, and if this package was distributed via jar these [manifest requirements](https://github.com/OneDrive/onedrive-sdk-android/blob/master/onedrivesdk/src/main/AndroidManifest.xml) would not be exposed.

Is this a hard requirement for how you consume dependencies?

**Comment by isabsent** [comment]
You are right about Manifest, but for example Google distributes their Drive access [libraries](https://github.com/google/google-api-java-client-samples/tree/master/cloudnotes-preview-android-sample/libs) as jar-files ([example](https://github.com/google/google-api-java-client-samples/tree/master/cloudnotes-preview-android-sample)) with the same [manifest requirements](https://github.com/google/google-api-java-client-samples/blob/master/cloudnotes-preview-android-sample/AndroidManifest.xml)

It isn't a hard requirement for how to consume dependencies, but sometimes it result in unreasonable complication with Gradle or Maven.

**Comment by peternied** [comment]
Those libraries pre-date the official usage of gradle tools for scenarios like manifest merging. Making a (more) error prone jar available is just inviting a bad experience using the OneDrive SDK for Android.

I'm going to close out this issue for now, I'm happy to have more of a dialog if there are scenarios that I'm missing.
