### ISSUE TITLE
Profile information!

### ISSUE THREAD

**Issue by AnilSony** [OneDrive/onedrive-sdk-android#121]
Hi, 

My name is Anil, I need to get Profile information like email, phone, etc.
It's possible?, I didn't see any API's supporting this, I got only Authentication type not the profile details. Please Help.

**Comment by nikz-dev** [comment]
I also need email that is used for login but don't see any API. [LiveSdk](https://github.com/liveservices/LiveSDK-for-Android) provide info using 
```
JSONObject result = LiveOperation.getResult();
String name = result.getString("name");
```

But unable to find similar type of API in [this](https://github.com/OneDrive/onedrive-sdk-android) sdk.

**Comment by nikz-dev** [comment]
Find a way to get username, may be helpful
  ```
Drive drive = oneDriveClient.getDrive().buildRequest().get();
String name = drive.owner.user.displayName;
```

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
