### ISSUE TITLE
How to switch between accounts ?

### ISSUE THREAD

**Issue by fiasko131** [OneDrive/onedrive-sdk-android#124]
I can not find a way to create multiple accounts and pass from one to the other. The code that i use to create one Account in my app:
````java
final DefaultCallback<IOneDriveClient> callback = new DefaultCallback<IOneDriveClient>(getActivity()) {
                            @Override
                            public void success(final IOneDriveClient result) {

                                mOneDriveClient = result;
                                mOneDriveClient
                                        .getDrive()
                                        .buildRequest()
                                        .get(new ICallback<com.onedrive.sdk.extensions.Drive>() {


                                            @Override
                                            public void success(final com.onedrive.sdk.extensions.Drive onedrive) {
                                               
                                                new Thread(new Runnable() {
                                                    @Override
                                                    public void run() {
														//In this method I retrieve the account infos:
														//DriveId, quotas, displayName ....
                                                        createOneDriveAccount(onedrive);
                                                    }
                                                }).start();
                                            }
                                            @Override
                                            public void failure(ClientException ex) {
                                                Toast.makeText(getActivity(),"pas bon", Toast.LENGTH_SHORT)
                                                        .show();
                                            }
                                        });
                            }
                            @Override
                            public void failure(final ClientException error) {

                            }
                        };
                        new OneDriveClient
                                .Builder()
                                .fromConfig(createConfig())
                                .loginAndBuildClient(getActivity(), callback);
````
But I can not renew the operation to create and register another account. How can I access the microsoft login page again?

**Comment by daboxu** [comment]
probably you can try
```java
 oneDriveClient.getAuthenticator().logout();
```

to logout the current account you are using?

**Comment by fiasko131** [comment]
@daboxu If I do this I can get a new client but if I want to reconnect to the precedent I have to redo a login with the authorization. How do I reconnect with the the obtained driveId (or accestoken?) and save in a file for example, without going back through the process?
So as with the other providers of cloud I can have several sessions and pass an object from one to the other.
Thank you.

**Comment by daboxu** [comment]
that's a little bit tricky, if an access token works for your case, you can get it from the authenticator.
```java
oneDriveClient.getAuthenticator().getAccountInfo().getAccessToken();
```

The MSA Authenticator we provided for OneDriveSDK is not intended for handling multiple sessions of user due to the underlying LiveAuthClient. So probably you can implements your own IAuthenticator which delegate the auth login work to MSAAuthenticator while store the access tokens by yourself?

And welcome to provide this feedback to the new [Graph SDK](https://github.com/microsoftgraph/msgraph-sdk-android-msa-auth-for-android-adapter) and [Graph Authenticator](https://github.com/microsoftgraph/msgraph-sdk-android-msa-auth-for-android-adapter)

**Comment by fiasko131** [comment]
Yes i can get the acces tokens but i don't find the method to build a client with it... I don't understand why it 's so tricky to manage multiple session with this sdk. I will search with MSA Authenticator ...

**Comment by huntext17** [comment]
hi, were you able to get it working or find a workaround for this?

**Comment by fiasko131** [comment]
@huntext17
No, and i don't understand why this basic feature is not supported!

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
