### ISSUE TITLE
Question on Upload.

### ISSUE THREAD

**Issue by isabsent** [OneDrive/onedrive-sdk-android#13]
As we can see in [Upload example](https://github.com/OneDrive/onedrive-sdk-android/blob/26f0db85d799f5477fbe902bc8c1f2e706e314de/docs/items.md#upload-a-file) it is necessary to have file as byte array for uploading, that is a problem for big file. It would be nice to add upload capabilitiy from InputStream in this SDK:

```
final String filename = "The Filename.txt";
final InputStream[] inputStream = new SomeInputStream(...); /* Not necessatily from a file on file system */
final IProgressCallback<Item> callback = new IProgressCallback<Item>() {
    public void success(final Item item) {
        Toast.makeText(getActivity(), "Item uploaded", Toast.LENGTH_LONG).show();
    }
    ...
    // Handle progress
    // Handle failure
}

oneDriveClient
    .getDrive()
    .getItems(ItemId)
    .getChildren()
    .byId(filename)
    .getContent()
    .buildRequest()
    .put(inputStream, callback);
```

**Comment by peternied** [comment]
That is a great ask, I've been working on a wrapper for using the chunked upload APIs, which I believe to be the more durable path for larger uploads.  When that features has a pull request out I'll make sure to include you for comments/feedback.

**Comment by isabsent** [comment]
Thanks! 

There is one more question about **synchronous** upload call. As I understand, the synchronous upload call looks like:

```
oneDriveClient
    .getDrive()
    .getItems(ItemId)
    .getChildren()
    .byId(filename)
    .getContent()
    .buildRequest()
    .put(fileContents);
```

If it is, I can't find the way to set ProgressListener to get an upload progress as it was possible in your package com.microsoft.onedriveaccess  (before onedrive-sdk-android release). Are you going to provide opportunity for setting of ProgressListener in the synchronous upload call?

**Comment by peternied** [comment]
I don't have plans to include progress callbacks for synchronous methods, if you wanted to perform this action in a synchronous-ish way with a IProgressCallback you could do the following at your own risk:

``` java
final AtomicReference<Item> result = new AtomicReference<>();
final SimpleWaiter waiter = new SimpleWaiter();
final IProgressCallback<Item> callback = new IProgressCallback<Item>() {
    @Override
    public void progress(final long current, final long max) {
        // Handle updates
    }

    @Override
    public void success(final Item item) {
        result.set(item);
        waiter.signal();
    }

    @Override
    public void failure(final ClientException ex) {
        // Handle errors
        waiter.signal();
    }
};

oneDriveClient
        .getDrive()
        .getItems(ItemId)
        .getChildren()
        .byId(filename)
        .getContent()
        .buildRequest()
        .put(fileContents, callback);
waiter.waitForSignal();
// Use result.get();
```

Note: this is the method to how some of the async methods our dependent libraries were [unwound](https://github.com/OneDrive/onedrive-sdk-android/blob/master/onedrivesdk/src/main/java/com/onedrive/sdk/authentication/MSAAuthenticator.java#L154) to be synchronous

**Comment by isabsent** [comment]
Thanks for clarification.
