### ISSUE TITLE
When there're lots of files under one folder, getNextPage() always returns non-null

### ISSUE THREAD

**Issue by EmmaZhang11** [OneDrive/onedrive-sdk-android#130]
There's 200 files under one folder (no sub folder), they're retrieved by iteratoring  items in page.getCurrentPage(), but getNextPage() always return a non-null object, which makes process can't stop. Please solve this issue.
                                }

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
