### ISSUE TITLE
- 314: Failed silent login, interactive login required

### ISSUE THREAD

**Issue by PiYun01** [OneDrive/onedrive-sdk-android#132]
- 314: Failed silent login, interactive login required
                                                                                               com.onedrive.sdk.authentication.ClientAuthenticatorException: Failed silent login, interactive login required
                                                                                                   at com.onedrive.sdk.authentication.MSAAuthenticator$5.onAuthComplete(MSAAuthenticator.java:312)
                                                                                                   at com.microsoft.services.msa.LiveAuthClient$3.doInBackground(LiveAuthClient.java:484)
                                                                                                   at com.microsoft.services.msa.LiveAuthClient$3.doInBackground(LiveAuthClient.java:473)
                                                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                   at java.lang.Thread.run(Thread.java:818)

11-27 18:58:17.494 25806-26413/com.bloomlife.luobo D/MSAAuthenticator[login] - 229: Waiting for MSA callback
11-27 18:58:17.500 25806-26415/com.bloomlife.luobo I/LiveAuthClient: No refresh token available, sorry!
11-27 18:58:17.500 25806-26415/com.bloomlife.luobo I/LiveAuthClient: All tokens expired, you need to call login() to initiate interactive logon
11-27 18:58:17.502 25806-26415/com.bloomlife.luobo D/MSAAuthenticator$2[onAuthComplete] - 201: Received invalid login failure from silent authentication with MSA, ignoring.
11-27 18:58:17.502 25806-25806/com.bloomlife.luobo D/WebView: WebView<init>
11-27 18:58:17.505 25806-25806/com.bloomlife.luobo I/cr_EUI_AwContents: create AwContents
11-27 18:58:17.511 25806-25806/com.bloomlife.luobo D/cr_Ime: [InputMethodManagerWrapper.java:27] Constructor
11-27 18:58:17.513 25806-25806/com.bloomlife.luobo D/AwPasswordHandler: getInstance, sInstance = org.chromium.android_webview.AwPasswordHandler@9ad624b
11-27 18:58:17.514 25806-25806/com.bloomlife.luobo W/chromium: [WARNING:password_handler.cc(33)] create-->contents = 0xd19a6b00, delegate = 0xc6363b18
11-27 18:58:17.514 25806-25806/com.bloomlife.luobo W/chromium: [WARNING:password_handler.cc(41)] attaching to web_contents 
11-27 18:58:17.514 25806-25806/com.bloomlife.luobo W/chromium: [WARNING:jni_string.cc(28)] ConvertJavaStringToUTF8 called with null string.
11-27 18:58:17.514 25806-25806/com.bloomlife.luobo W/cr_AwContents: onDetachedFromWindow called when already detached. Ignoring
11-27 18:58:17.515 25806-25806/com.bloomlife.luobo D/cr_Ime: [InputMethodManagerWrapper.java:56] isActive: false
11-27 18:58:17.517 25806-25806/com.bloomlife.luobo D/WebView: loadUrl=https://login.live.com/oauth20_authorize.srf?client_id=fae8834-00bb-4f39-a786-8c491a283067&scope=office.onenote_create%20office.onenote_update_by_app%20wl.offline_access&display=android_phone&response_type=code&redirect_uri=https%3A%2F%2Flogin.live.com%2Foauth20_desktop.srf
11-27 18:58:17.517 25806-25806/com.bloomlife.luobo I/cr_EUI_AwContents: loadUrl url:https://login.live.com/oauth20_authorize.srf?client_id=fae8834-00bb-4f39-a786-8c491a283067&scope=office.onenote_create%20office.onenote_update_by_app%20wl.offline_access&display=android_phone&response_type=code&redirect_uri=https%3A%2F%2Flogin.live.com%2Foauth20_desktop.srf
11-27 18:58:17.517 25806-25806/com.bloomlife.luobo E/wqqgt: loadUrl() isDestroyed=false mNativeAwContents=-777113088
11-27 18:58:17.522 25806-25806/com.bloomlife.luobo W/chromium: [WARNING:jni_string.cc(28)] ConvertJavaStringToUTF8 called with null string.
11-27 18:58:17.540 25806-26083/com.bloomlife.luobo I/Document::attach:  line = 2169
11-27 18:58:17.541 25806-26083/com.bloomlife.luobo I/chromium: [INFO:render_view_impl.cc(3824)] RenderViewImpl::UpdateH5VideoPref() this: 0xd1c7f000 h5_video_json_data:  h5_video_user_operate_state: -1
11-27 18:58:17.542 25806-26083/com.bloomlife.luobo I/chromium: [INFO:render_view_impl.cc(3824)] RenderViewImpl::UpdateH5VideoPref() this: 0xd1c7f000 h5_video_json_data:  h5_video_user_operate_state: -1
11-27 18:58:17.543 25806-26073/com.bloomlife.luobo I/chromium: [INFO:resource_loader.cc(162)] EUI_ResourceLoader: Start request， url: https://login.live.com/oauth20_authorize.srf?client_id=fae8834-00bb-4f39-a786-8c491a283067&scope=office.onenote_create%20office.onenote_update_by_app%20wl.offline_access&display=android_phone&response_type=code&redirect_uri=https%3A%2F%2Flogin.live.com%2Foauth20_desktop.srf
11-27 18:58:17.555 25806-25806/com.bloomlife.luobo W/chromium: [WARNING:jni_string.cc(28)] ConvertJavaStringToUTF8 called with null string.
11-27 18:58:17.556 25806-26083/com.bloomlife.luobo I/chromium: [INFO:render_view_impl.cc(3824)] RenderViewImpl::UpdateH5VideoPref() this: 0xd1c7f000 h5_video_json_data:  h5_video_user_operate_state: -1
11-27 18:58:17.610 25806-25806/com.bloomlife.luobo I/chromium: [INFO:synchronous_compositor_impl.cc(464)] [RegisterProgressCheckCallback] chromium.skipbeginmainframe=[] enable=[0]
11-27 18:58:17.612 25806-26083/com.bloomlife.luobo I/chromium: [INFO:ScrollbarThemeDraggable.cpp(77)] drag_scroll blink paint 0
11-27 18:58:17.612 25806-26083/com.bloomlife.luobo I/chromium: [INFO:native_theme_android.cc(66)] drag_scroll ui paint 0
11-27 18:58:17.641 25806-25806/com.bloomlife.luobo W/cr_AwContents: shouldIgnoreNavigation called
11-27 18:58:17.644 25806-26073/com.bloomlife.luobo W/WebViewCallback: doUrlRequestFiltering 
11-27 18:58:17.652 25806-26073/com.bloomlife.luobo W/chromium: [WARNING:net_errors_posix.cc(23)] EUI_Socket MapSystemError, os_error = Network is unreachable
11-27 18:58:17.681 25806-25806/com.bloomlife.luobo I/EUI_WebViewCallback: onPageStarted url:https://login.live.com/oauth20_authorize.srf?client_id=fae8834-00bb-4f39-a786-8c491a283067&scope=office.onenote_create%20office.onenote_update_by_app%20wl.offline_access&display=android_phone&response_type=code&redirect_uri=https%3A%2F%2Flogin.live.com%2Foauth20_desktop.srf
11-27 18:58:18.859 25806-26073/com.bloomlife.luobo I/chromium: [INFO:resource_loader.cc(249)] EUI_ResourceLoader: OnReceiveRedirect， url: https://login.live.com/oauth20_authorize.srf?client_id=fae8834-00bb-4f39-a786-8c491a283067&scope=office.onenote_create%20office.onenote_update_by_app%20wl.offline_access&display=android_phone&response_type=code&redirect_uri=https%3A%2F%2Flogin.live.com%2Foauth20_desktop.srf
11-27 18:58:18.860 25806-25806/com.bloomlife.luobo W/cr_AwContents: shouldIgnoreNavigation called
11-27 18:58:18.862 25806-25806/com.bloomlife.luobo W/AwContentsClientBridge: shouldOverrideUrlLoading called
11-27 18:58:18.862 25806-25806/com.bloomlife.luobo W/cr_AwContentsClient: shouldIgnoreNavigation called, has client
11-27 18:58:18.862 25806-25806/com.bloomlife.luobo W/WebViewCallback: shouldOverrideUrlLoading called
11-27 18:58:18.862 25806-25806/com.bloomlife.luobo W/WebViewCallback: shouldOverrideUrlLoading called finish: false
11-27 18:58:18.864 25806-26073/com.bloomlife.luobo W/WebViewCallback: doUrlRequestFiltering 
11-27 18:58:18.868 25806-26073/com.bloomlife.luobo W/chromium: [WARNING:net_errors_posix.cc(23)] EUI_Socket MapSystemError, os_error = Network is unreachable
11-27 18:58:18.869 25806-25806/com.bloomlife.luobo I/EUI_WebViewCallback: onPageStarted url:https://login.live.com/err.srf?lc=2052#error=unauthorized_client&error_description=The+client+does+not+exist.+If+you+are+the+application+developer%2c+configure+a+new+application+through+the+application+management+site+at+https://apps.dev.microsoft.com/.
11-27 18:58:20.085 25806-26073/com.bloomlife.luobo I/chromium: [INFO:resource_loader.cc(668)] EUI_ResourceLoader: RespnseCompleted， url: https://login.live.com/err.srf?lc=2052#error=unauthorized_client&error_description=The+client+does+not+exist.+If+you+are+the+application+developer%2c+configure+a+new+application+through+the+application+management+site+at+https://apps.dev.microsoft.com/.
11-27 18:58:20.087 25806-26083/com.bloomlife.luobo I/Document::attach:  line = 2169
11-27 18:58:20.089 25806-25806/com.bloomlife.luobo W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 25806
11-27 18:58:20.130 25806-25806/com.bloomlife.luobo W/chromium: [WARNING:password_handler.cc(212)] OnPasswordFormsRendered called
11-27 18:58:20.130 25806-25806/com.bloomlife.luobo W/chromium: [WARNING:aw_password_handler_delegate_impl.cc(215)] IsSavePasswordEnabled ret is 1
11-27 18:58:20.130 25806-25806/com.bloomlife.luobo W/chromium: [WARNING:password_handler.cc(217)] OnPasswordFormsRendered can_save = 0
11-27 18:58:20.130 25806-26083/com.bloomlife.luobo I/chromium: [INFO:ScrollbarThemeDraggable.cpp(77)] drag_scroll blink paint 0
11-27 18:58:20.131 25806-26083/com.bloomlife.luobo I/chromium: [INFO:native_theme_android.cc(66)] drag_scroll ui paint 0
11-27 18:58:20.133 25806-25806/com.bloomlife.luobo I/EUI_WebViewCallback: onPageFinished url:https://login.live.com/err.srf?lc=2052#error=unauthorized_client&error_description=The+client+does+not+exist.+If+you+are+the+application+developer%2c+configure+a+new+application+through+the+application+management+site+at+https://apps.dev.microsoft.com/.
11-27 18:58:20.135 25806-26073/com.bloomlife.luobo I/chromium: [INFO:resource_loader.cc(162)] EUI_ResourceLoader: Start request， url: https://login.live.com/favicon.ico
11-27 18:58:20.140 25806-26073/com.bloomlife.luobo I/chromium: [INFO:resource_loader.cc(668)] EUI_ResourceLoader: RespnseCompleted， url: https://login.live.com/favicon.ico
11-27 18:58:20.164 25806-25806/com.bloomlife.luobo I/EUI_WebViewCallback: onPageCommitVisible url:https://login.live.com/err.srf?lc=2052#error=unauthorized_client&error_description=The+client+does+not+exist.+If+you+are+the+application+developer%2c+configure+a+new+application+through+the+application+management+site+at+https://apps.dev.microsoft.com/.
11-27 18:58:20.164 25806-25806/com.bloomlife.luobo W/WebViewCtrlFilter: Url is https://login.live.com/err.srf?lc=2052#error=unauthorized_client&error_description=The+client+does+not+exist.+If+you+are+the+application+developer%2c+configure+a+new+application+through+the+application+management+site+at+https://apps.dev.microsoft.com/.
11-27 18:58:20.164 25806-25806/com.bloomlife.luobo W/WebViewCtrlFilter: filter result is true
11-27 18:58:20.178 25806-25806/com.bloomlife.luobo D/LeAgnes: rtls_1_4 :  pn: com.bloomlife.luobo nt: WIFI ul: https://login.live.com/err.srf?lc=2052#error=unauthorized_client&error_description=The+client+does+not+exist.+If+you+are+the+application+developer%2c+configure+a+new+application+through+the+application+management+site+at+https://apps.dev.microsoft.com/. tt: Microsoft 帐户

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
