### ISSUE TITLE
Some functions required passing in an Activity as context.

### ISSUE THREAD

**Issue by opaquewarellc** [OneDrive/onedrive-sdk-android#135]
I am trying use this in a JobService which isn't an Activity. A service context can not be cast to an Activity.
Why can't it use the more generic "Context" instead of "Activity".
(e.g. loginAndBuildClient(final **Activity activity**, final ICallback<IOneDriveClient> callback) )

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
