### ISSUE TITLE
How to fetch next page with searchRequest?

### ISSUE THREAD

**Issue by mcsong** [OneDrive/onedrive-sdk-android#141]
Hello, 
I can't find how to fetch next page with searhRequest? 

I did call first like this. 

mDriveSearchCollectionPage = mGraphServiceClient.getMe().getDrive()
						//.buildRequest(searchOptions).expand("thumbnails").get();
						.getSearch(queryValue).buildRequest()
						.select("id, folder, file, name, size, lastModifiedDateTime, createdDateTime, webUrl")
						.expand("thumbnails")
						.top(500)
						.get();

And, I try to use this code for fetching next page. 

	while (items != null) {
	
				if (mDriveSearchCollectionPage.getNextPage() == null)
					break;

				items = mDriveSearchCollectionPage
						.getNextPage()
						.buildRequest()
						.get()
						.getCurrentPage();
			}

But, it doesn't not works.
If someone know how to fetch next page with SearchRequest, please help me. 

Thank you,

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
