### ISSUE TITLE
How to create oneDriveClient object?, it showing incompatible type, required com.onedrive.sdk.extensions.IOneDriveClient Found: void

### ISSUE THREAD

**Issue by zeeshanjaved** [OneDrive/onedrive-sdk-android#142]
final MSAAuthenticator msaAuthenticator = new MSAAuthenticator() {
        @Override
        public String getClientId() {
            return "<msa-client-id>";
        }
        @Override
        public String[] getScopes() {
            return new String[] { "onedrive.appfolder" };
        }
    };
    final ADALAuthenticator adalAuthenticator = new ADALAuthenticator() {
        @Override
        public String getClientId() {
            return "9e2bad38-ea0c-44a7-b666-736a4e642dc3";
        }
        @Override
        protected String getRedirectUrl() {
            return "https://localhost";
        }
    };

    final IClientConfig oneDriveConfig = DefaultClientConfig.createWithAuthenticators(
            msaAuthenticator,
            adalAuthenticator);

    final DefaultCallback<IOneDriveClient> callback = new DefaultCallback<IOneDriveClient>(activity) {
        @Override
        public void success(final IOneDriveClient result) {
            // OneDrive client created successfully.
        }

        @Override
        public void failure(final ClientException error) {
            // Exception happened during creation.
        }
    };

    abstract private class DefaultCallback<T> implements ICallback<IOneDriveClient> {
        Activity activity;
        DefaultCallback(Activity activity){
            this.activity =activity;
        }
        public abstract void success(IOneDriveClient iOneDriveClient);
        public abstract void failure(ClientException e);
    }

    final IOneDriveClient oneDriveClient = new OneDriveClient.Builder()
            .fromConfig(oneDriveConfig)
            .loginAndBuildClient(getActivity(), callback);

**Comment by zeeshanjaved** [comment]
I am having trouble while creating IOneDriveClient object. please help me!
final IOneDriveClient oneDriveClient = new OneDriveClient.Builder()
        .fromConfig(oneDriveConfig)
        .loginAndBuildClient(getActivity(), callback);

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
