### ISSUE TITLE
**Get a OneDriveClient object** sample code is outdated

### ISSUE THREAD

**Issue by ajpeacock0** [OneDrive/onedrive-sdk-android#143]
The sample code under the [Get a OneDriveClient object](https://github.com/OneDrive/onedrive-sdk-android#23-get-a-onedriveclient-object) section has the following
```
final DefaultCallback<IOneDriveClient> callback = new DefaultCallback<IOneDriveClient>(activity) {...};     
final IOneDriveClient oneDriveClient = new OneDriveClient.Builder()
                                            .fromConfig(oneDriveConfig)
                                            .loginAndBuildClient(getActivity(), callback);
```
The `OneDriveClient.Builder.loginAndBuildClient` function is now async, returning the `IOneDriveClient` in the given `DefaultCallback`. The sample code still expects a `IOneDriveClient` value returned from `loginAndBuildClient` however it's return type is now void.

A simple fix but confusing to first time readers.

**Comment by hollaus** [comment]
I agree with  @ajpeacock0, the sample is outdated. I simply replaced DefaultCallback with ICallback:

```
ICallback<IOneDriveClient> callback = new ICallback<IOneDriveClient>() {
    @Override
    public void success(IOneDriveClient iOneDriveClient) {

    }

    @Override
    public void failure(ClientException ex) {

    }
};

new OneDriveClient.Builder()
        .fromConfig(oneDriveConfig)
        .loginAndBuildClient(activity, callback);
```

**Comment by josephnarai** [comment]
Thank you @hollaus lifesaver... thought I was going crazy - someone should really update the examples!

**Comment by ArashM98** [comment]
so what happen to the rest of sample ?  * get root folder
how to get oneDriveClient object to call it's method?

oneDriveClient
    .getDrive()
    .getRoot()
    .buildRequest()
    .get(new ICallback<Item>() {
  @Override
  public void success(final Item result) {
    final String msg = "Found Root " + result.id;
    Toast.makeText(getActivity(), msg, Toast.LENGTH_SHORT)
        .show();
  }
  ...
  // Handle failure case
});

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
