### ISSUE TITLE
No more than 200 Items are downloaded

### ISSUE THREAD

**Issue by Azar56** [OneDrive/onedrive-sdk-android#144]
As getNextPage() always returns null no more than 200 Items can be downloaded.
This is a serious limitation which makes this library unsuitable for my purposes.

In a downloaded version of this project I included the missing code in the module BaseItem.
However this module is flagged "This file is generated by a tool and any changes will be overwritten".
So my solution does not have a general character. However, my fix worked.

A second correction in the file ItemCollectionPage.java fixed the problem that getNextPage() stays forever != null even if there are no more second pages. Use for this the following code

    public ItemCollectionPage(final BaseItemCollectionResponse response, IItemCollectionRequestBuilder builder) {
        super(response, builder);
        if (response.nextLink == null) super.setNextPage(null); // Inserted this new line
    }

Please address this issue asap, as the usage of this library is seriously limited at the moment.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
