### ISSUE TITLE
Abondaoned? Any plans to  switch to msa-auth-for-android

### ISSUE THREAD

**Issue by NLLAPPS** [OneDrive/onedrive-sdk-android#145]
Hi, is this SDK abandoned?  

It took me couple of days to find proper information about all MS projects related to Android and get a picture of it.

From what I understand  [https://github.com/OfficeDev/msa-auth-for-android
](https://github.com/OfficeDev/msa-auth-for-android) and [https://github.com/microsoftgraph/msgraph-sdk-android-msa-auth-for-android-adapter](https://github.com/microsoftgraph/msgraph-sdk-android-msa-auth-for-android-adapter) is the new/modern way of authentication with MS Graph.

It looks like they also have capabilities of OneDrive for Android but I am not sure if supports all.

Can someone shed a light on this confusion and whether is OnDrive Android SDK is abandoned.

I have already spent a week on getting silent login working with OneDrive Android SDK and just realized one of its dependencies `msa-auth` relies on deprecated Apache HTTP client and causes crash unless you add 

`   <uses-library
            android:name="org.apache.http.legacy"
            android:required="false"/>`

**Comment by bubbleguuum** [comment]
I asked myself the same question a few days ago when dealing with the old LiveSDK API that is now entirely retired. This SDK works fine and I went with it because it seemed a bit more simple than the more general MS graph android SDK. Although this SDK seems largely unmaintained.

Also see:
https://github.com/microsoftgraph/msgraph-sdk-android/issues/94

**Comment by NLLAPPS** [comment]
Live SDK actually lives in msa. Have look it is exactly same code made synchronous by locks and api end points and json objects of new graph implemented.

Too much legacy code. It is unbelievable that a multi billion dollar company cannot assigne few engineer ls to keep this updated

On January 13, 2019 5:02:17 PM UTC, bubbleguuum <notifications@github.com> wrote:

I asked myself the same question a few days ago when dealing with the old LiveSDK API that is now entirely retired. This SDK works fine and I went with it because it seemed a bit more simple than the more general MS graph android SDK. Although this SDK seems largely unmaintained.

**Comment by Azar56** [comment]
For me there was no doubt that I will use this sdk only

1) if I get the sources
2) I am able to generate it locally
3) I am able to maintain it myself.

After a week's effort I have achieved this goals mostly. I really hope there are no more errors.

However, I am not fully satisfied with the current situation. My experience in handling this sdk has not become part of the community. I would have expected some guidance on how to do this, as I am a novice to the open source world.

So the answer to the question: "Is this sdk abandoned?" is partly yes.
However , the problem of a legacy code library can be solved

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
