### ISSUE TITLE
Logout issue with new Async Object of IOneDriveClient

### ISSUE THREAD

**Issue by sam-devstudio** [OneDrive/onedrive-sdk-android#147]
Logout issue with new Async Object of IOneDriveClient. User have to first login to get the IOneDriveClient object and if user is not already logged in of have revoked access from web then before logout we have to enter credentials on Sign in screen or give permissions again. That's really embarassing that before logout we show login screen. Thanks

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
