### ISSUE TITLE
java.lang.NoClassDefFoundError: org.jacoco.agent.rt.internal

### ISSUE THREAD

**Issue by isabsent** [OneDrive/onedrive-sdk-android#15]
When trying to create new Item:

```
Item item = new Item();
```

I have immediately got an exception:

```
java.lang.NoClassDefFoundError: org.jacoco.agent.rt.internal_773e439.Offline
        at com.onedrive.sdk.extensions.Item.$jacocoInit(Item.java)
        at com.onedrive.sdk.extensions.Item.<init>(Item.java)
```

I have never used org.jacoco.agent.rt.internal and was not able to find any references of this package in your [example](https://github.com/OneDrive/onedrive-explorer-android). Who is **jacocoInit** and what is a reason of this strange exception?

**Comment by peternied** [comment]
I would associate `org.jacoco` with the code coverage tooling from Androids build support libraries.  Do you have a gist of the gradle output?

**Comment by isabsent** [comment]
I am using Intellij IDEA with gradle

```
com.android.tools.build:gradle:1.5.0
```

What should I do to get a gist of the gradle output?

**Comment by peternied** [comment]
@isabsent I just meant to capture the complete build output into a file and paste it into https://gist.github.com/

And I haven't tried using the build tools 1.5.0, I'm using 1.3.0 currently (not that it shouldn't be forward compatible...)

**Comment by isabsent** [comment]
Sorry, it was my fault. Instead of using 

```
compile('com.onedrive.sdk:onedrive-sdk-android:1.0.1')
```

I have abused your SDK by means of extracting jar-file from it and have attached the jar to my project as a:

```
compile files('libs/onedrive-android-sdk-1.0.1.jar')
compile 'com.microsoft.services.msa:msa-auth:0.8.4'
compile ('com.microsoft.aad:adal:1.1.7')
```

**Comment by peternied** [comment]
Does that mean that using a jar runs into other dependency issues?

**Comment by isabsent** [comment]
No. I suppose that my way to get jar from aar is some kind of "hack" and leads to this problem.

**Comment by peternied** [comment]
You might be hitting this because you used a debug assembly, you try a retail version, it might work better, however I think you'll have the easiest ride with Gradle/Maven.

**Comment by amitav13** [comment]
@isabsent (and others who might run into this) This error was resolved for me on a different project by specifying testCoverageEnabled = true in gradle. Since this is false by default, it causes apps to bonk.
