### ISSUE TITLE
Issue while uploading the image.

### ISSUE THREAD

**Issue by Kumar321** [OneDrive/onedrive-sdk-android#151]
Hi Am getting this error. Please check this:

320: OneDrive Service exception Error code: invalidRequest
    Error message: ObjectHandle is Invalid
    
    POST https://api.onedrive.com/v1.0/drive/items/Documents%3A/Scan%2021-05-2019_4.jpg_3.jpg_1.jpg%3A/action.createUploadSession
    X-RequestStats : SDK-Version=Android-v1.3.1
    Authorization : bearer EwAYA61DBAAUcSSzoTJJsy+XrnQXgAKO5cj4yc8AAZXWrukAPa6FTzpbc1tSLGR8ZlQs0SxTxbHsikzD7gSO9xRgdcxMPXU5CeiYcgibXYv2YeQYOi2g0+r7Nk+HvNeMnGNR7xgpbgyAbxpVWotL1ZCno9x9U94kwJ6clBs0ky7UQOn6pm/FXiQ1Z+/jg4tk0lZUTNA7rLknIAtAcf21YcUaN8oFcE8uASuxSD6nBj4nS7sk7x+8lTZxBjLjfNeiO/SiQHwFZCYhrhGdu+dwCKlAhJ3kR7yJGRHg5VUy6cOFz50689Nh9M3U+knxxOWFy7O+/dhOQKLfEJwSN7yJssSHxCvXIiOUi/YlnOXs6i9m7DgcRLsc0ksAFwOWuFMDZgAACCopfU9Hn4f06AFUiCQHkap2bAwrDuh8gEp8dXgQdKP9dobCfCCo9KzLbPl1HXi3VB3UI4KC6dPbvUuSeKoql3Q5wBD+217MWZnuOCY14IMizZuhrE1cV48oVmJdGra8cTJpZRHqa/CtVdn8g5IFItwvnGiwPwc5vhyomaifkuzAtWYGlf375LxuWDV9pH5CAG+XgZfMEEdorf2G72+BuGabvZn3dTVL8gLzI2Hr1bdxY/9/88w7+wvt1QM611bKqpdOO1FMvNUgAogRArGal+eteYfrf1UqhmrwEXSxC9fVb8pmD6+bg08DouCpZhLAIq7WLFbmx1uPQL8+gJN1HSb3UQVLcAn35CpndfHPH0Qxe6WrSbAP7OzfTd7dzUj/LZdDlx6kk+s0Dt9wE6WQgKpfr+FGAxE930FIROayO3ahtuNqrejzEZynw7g5JrKLkvguG4tZdQ3kf1LXgtuZWM9Pbf7nAvbtPqqIVNZ4XE2X5uolVHz23C54nWB7JbMlsgga8fDnxzluNxTJsFxjq6narBSR1wpkUx6LnDYDN2v/9GZCGLcnce766E09OcIk2s14ZOsSAKUYnDdIGQ0g/K6nYCIAMYhzoI3UXdpkkZqgP5ikO6+cwuH18JI9Skvr9sXoG3MSvnguq2eps4ZZoBmLTBsC
    {"item":{"name":"Scan 21-05-2019_4.jpg_3.jpg_1.jpg"}}
    
    400 : Bad Request
    X-VroomVersion : v1.0
    X-QosStats : {"ApiId":0,"ResultType":2,"SourcePropertyId":0,"TargetPropertyId":42}
    X-ThrowSite : 5ce0.eb9a
    X-AsmVersion : UNKNOWN; 19.257.520.2004
    P3P : CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
    X-Android-Received-Millis : 1558766849228
    X-MSEdge-Ref : Ref A: D0A85B9270A04038ADD7C826B3C7B958 Ref B: BOM02EDGE0312 Ref C: 2019-05-25T06:47:22Z
    X-MSNSERVER : BL6PPF8A4226F2B
    Date : Sat, 25 May 2019 06:47:22 GMT
    Via : 1.1 AM3PPF5DA09B034 (wls-colorado)
    X-Android-Selected-Protocol : http/1.1
    Strict-Transport-Security : max-age=31536000; includeSubDomains
    X-WLSPROXY : AM3PPF5DA09B034
    Cache-Control : no-store
    X-Android-Response-Source : NETWORK 400
    MS-CV : Tvzq/YDB2Eu6cPYDRUO0cA.0
    Vary : Accept,Accept-Language,Authorization,Prefer
    X-Android-Sent-Millis : 1558766848455
    Content-Type : application/json
    {
       "error": {
          "code": "invalidRequest",
          "message": "ObjectHandle is Invalid",
          "innererror": {
             "code": "invalidResourceId"
          }
       }
    }

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
