### ISSUE TITLE
How can i get authenticationToken from server use this SDK?

### ISSUE THREAD

**Issue by alexmaizerov** [OneDrive/onedrive-sdk-android#153]
I need authenticationToken for server side of mi application, to provide saving files by other users. 
I red whole documentation about rest API, and I fount that there are 2 ways :
1. response_type=code
2. response_type=token

Use android debugger I saw your login query, your query used responce_type=code, not token.
But server side return token and refresh token to me, and authToken == null every time.

How can i get authToken from your sdk?

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
