### ISSUE TITLE
File size is limited to 2GB.

### ISSUE THREAD

**Issue by KevinCWKevin** [OneDrive/onedrive-sdk-android#156]
Hi,
    I follow your sample code, used "createUploadProvider" to upload large files. But the variable of fileSize is limited to 2GB because the type of variable is Integer. Could you please provide a way to upload file with over 2GB?

Thanks

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
