### ISSUE TITLE
sharedWithMe not found

### ISSUE THREAD

**Issue by cool7203** [OneDrive/onedrive-sdk-android#158]
How can i list up shared folders/files with?

I tried to request the url such as "https://api.onedrive.com/v1.0/drive/sharedWithMe".

But the response is "Api Not Found" or "Invalid Request or Resource".

I can not find concerning documents about it.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
