### ISSUE TITLE
Error when creating OneDriveClient

### ISSUE THREAD

**Issue by David-Llop** [OneDrive/onedrive-sdk-android#159]
When I try to create a client in order to work with OneDrive from an app, the IDE doesn't recognise ``DefaultCallback``  as a Class or Interface. I've tried changing it to ``ICallback``, but then I get:

>incompatible types: void cannot be converted to IOneDriveClient

when creating the OneDriveClient.

Have I to import any extra library?

**Comment by panovvitalik** [comment]
@David-Llop Just replace example login code with this:
OneDriveClient.Builder oneDriveClientBuilder = new OneDriveClient.Builder().fromConfig(oneDriveConfig);
oneDriveClientBuilder.loginAndBuildClient(activity, callback);

**Comment by David-Llop** [comment]
@panovvitalik Thanks, I've just tried and works great
