### ISSUE TITLE
Error when try to auth

### ISSUE THREAD

**Issue by panovvitalik** [OneDrive/onedrive-sdk-android#160]
I have created my app under "portal.azure.com"
I have added a platform android to it. The portal is generated Uri for me like:  "msauth://my_package_name.... 
Then I try to login using this lib and after I inputted e-mail address I got following error page:

"We're unable to complete your request
invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application."

What is wronge?

**Comment by BhupeshDexati** [comment]
In Azure Portal, select your app and then go to Authentication page, Click on Add URI in Mobile and Desktop Application section and add "urn:ietf:wg:oauth:2.0:oob" as redirect URL and use the same in client app. This fixed the same issue for me, hope it would be helpful.

**Comment by panovvitalik** [comment]
> In Azure Portal, select your app and then go to Authentication page, Click on Add URI in Mobile and Desktop Application section and add "urn:ietf:wg:oauth:2.0:oob" as redirect URL and use the same in client app. This fixed the same issue for me, hope it would be helpful.

"Redirect URI" field is readonly in the azur portal.
When I try to input your value in the "Package name" field I recieve this error: "Less than 218 characters in length"

**Comment by BhupeshDexati** [comment]
You are trying with on wrong card...
Click on Add URI and add underlined code

![Annotation 2021-07-29 130444](https://user-images.githubusercontent.com/73809327/127451015-41549c8d-b064-48d9-a404-2ee729afcf51.png)

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
