### ISSUE TITLE
Is project alive?

### ISSUE THREAD

**Issue by panovvitalik** [OneDrive/onedrive-sdk-android#161]

**Comment by justforlxz** [comment]
It seems that Microsoft has unified all APIs, you can view this project [https://github.com/Azure-Samples/ms-identity-android-kotlin](https://github.com/Azure-Samples/ms-identity-android-kotlin)

**Comment by panovvitalik** [comment]
@justforlxz
I don't need unified apis, I need Onedrive api - uploading/downloadig files, creating directories and etc.
I saw your lib early, and it contains only some "login" functionality, that's all. 

Do you know Onedrive api sdk lib?

**Comment by justforlxz** [comment]
> @justforlxz
> I don't need unified apis, I need Onedrive api - uploading/downloadig files, creating directories and etc.
> I saw your lib early, and it contains only some "login" functionality, that's all.
> 
> Do you know Onedrive api sdk lib?

It’s the first time I have contact with onedrive’s api, I don’t understand, sorry.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
