### ISSUE TITLE
Error in example code (doc section 2.3)

### ISSUE THREAD

**Issue by arif10520** [OneDrive/onedrive-sdk-android#162]
Example is 
final IOneDriveClient oneDriveClient = new OneDriveClient.Builder()
                                            .fromConfig(oneDriveConfig)
                                            .loginAndBuildClient(getActivity(), callback);

But loginAndBuildClient does not return any object. please remove (final IOneDriveClient oneDriveClient = ) from the example.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
