### ISSUE TITLE
Refresh token doesn't expires on revoking app permission

### ISSUE THREAD

**Issue by BhupeshDexati** [OneDrive/onedrive-sdk-android#165]
In my app, I want to give user capability to revoke access from app only, since revoking access can only be done manually according to [this doc](https://docs.microsoft.com/hi-in/onedrive/developer/rest-api/getting-started/graph-oauth?view=odsp-graph-online#revoking-access)  , so I am opening that page for user in a separate activity with Webview inside the app.
Now on coming back from that page as the document says, refresh token should expire.

> When consent for an app is revoked, any refresh token previously provided to your application will no longer be valid. You will need to repeat the authentication flow to request a new access and refresh token from scratch.

But when I try coming back and trying silent login, it logs in user successfully, even all the drive file related methods are working properly, which is not right flow.
Please see if it's a bug, or let me know I am doing anything wrong in this flow

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
