### ISSUE TITLE
Could Anyone please tell me how to enable login with a business Account?

### ISSUE THREAD

**Issue by chenxi1991** [OneDrive/onedrive-sdk-android#166]
When I login with a Microsoft account,eventhing works fine.But with a business account,I can not login in.
![微信图片_20210914171806](https://user-images.githubusercontent.com/13568754/133231204-0e94b4ce-48b7-4187-af4d-c9c81f2a1bfc.jpg)

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
