### ISSUE TITLE
Unsafe Cipher Mode reported by GooglePlay

### ISSUE THREAD

**Issue by alexplanetart** [OneDrive/onedrive-sdk-android#168]
@peternied pe @phhusson @SandroMachado @cypressious @rgregg 
I used the this SDK（version 1.3.1） in my project  and Google detected some error messages. Is there any update for this problem?  https://support.google.com/faqs/answer/10046138
![image](https://user-images.githubusercontent.com/93108740/190302966-8df5afee-fc5d-4c4a-9370-40f21f996ef5.png)

**Comment by Pingapplepie** [comment]
Too many apps use this library to access one drive and encountered the same issue, hope we can get an update from here.

**Comment by peternied** [comment]
Looks like the ADAL dependent should be updated, see more recent versions from https://mvnrepository.com/artifact/com.microsoft.aad/adal

Someone could make a pull request to rev the version to use newer version, @alexplanetart how do you feel about taking this on?

**Comment by cypressious** [comment]
Please don't mention random people in issues.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
