### ISSUE TITLE
Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference

### ISSUE THREAD

**Issue by lee1996** [OneDrive/onedrive-sdk-android#169]
I am using your com.onedrive.sdk:onedrive-sdk-android:1.3.1 to access OneDrive cloud from my Android application. When I was downloading the file, following the steps in the document, when executing the get() method, I get the error ""Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference", please reply as soon as possible. 
![企业微信截图_9559e183-be6f-4830-8ce3-67b028d951c5](https://user-images.githubusercontent.com/17683617/223385655-40c08a29-a0ae-4083-96e5-c23612b3fb16.png)

**Comment by DuycuongPham** [comment]
I think this repo has been abandoned. I can't even sign in to my microsoft account when using msa-client-id has format like 00000000-0000-0000-0000-000000000000

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
