### ISSUE TITLE
Range request support.

### ISSUE THREAD

**Issue by isabsent** [OneDrive/onedrive-sdk-android#17]
Does current SDK support a **HTTP Range request**? This feature is necessary for applications using encrypted containers on a cloud. User doesn't need to download whole file (which may be huge), he need just a byte range [position, position + length - 1] to decrypt it with some key.

I didn't find how to specify such byte range in current SDK. A simplest way to give us range request support is to provide an Item with download URL as a String field. Having this downloadUrl we can get needed byte range with (all non-Android classes are from Apache packages): 

```
byte[] getByteArrayApache(String downloadUrl, long position, int length, String accessToken){
    HttpGet httpRequestGet = new HttpGet(downloadUrl);
    httpRequestGet.addHeader("Authorization", "Bearer " + accessToken); 
    httpRequestGet.addHeader("Range", "bytes=" + position + "-" + (position + length - 1));       
    HttpResponse response = new DefaultHttpClient().execute(httpRequestGet);        
    InputStream is = response.getEntity().getContent();
    return IOUtils.toByteArray(is);
}
```

**Comment by peternied** [comment]
When building requests optional options can be passed into the IRequestBuilder's build(...) method to add additional headers or parameters to a request, here is a quick example of how perform add range request header on a file download:

``` java
final List<Option> options = Arrays.asList((Option)new HeaderOption("Range", "bytes=0-128"));
oneDriveClient()
    .getDrive()
    .getItems(myItemId)
    .getContent()
    .buildRequest(options)
    .get(new ICallback<InputStream>() {
        @Override
        public void success(final InputStream inputStream) {
            // Handle success
        }
        @Override
        public void failure(final ClientException ex) {
            // Handle failure
        }
    });
```

I'll update the documentation to include this feature. Thanks!

**Comment by isabsent** [comment]
Thanks, it works.
