### ISSUE TITLE
Package is no longer available from JCenter

### ISSUE THREAD

**Issue by peeveen** [OneDrive/onedrive-sdk-android#171]
Now that [that sun has finally set on JCenter](https://jfrog.com/blog/jcenter-sunset/), it appears that this package has not been moved over to Maven Central, and so is completely unavailable (unless you luckily have a cached copy of the JAR/AAR on a machine somewhere).

**Comment by wikirsch** [comment]
Unfortunately, I can no longer compile my app that uses the OneDrive SDK for Android. Does anyone have an idea how this problem could be solved?

**Comment by peeveen** [comment]
> Unfortunately, I can no longer compile my app that uses the OneDrive SDK for Android. Does anyone have an idea how this problem could be solved?

@wikirsch

I still had a copy of the necessary files cached locally. If you want them, they're in the `app/obsoleteLibs` folder in [this project](https://github.com/peeveen/beatprompter).

Have a look at the `build.gradle` and `app/build.gradle` files for how I've had to reference them now (the `flatDir` and `@aar` parts).

**Comment by wikirsch** [comment]
@peeveen 
Thank you so much!! This saved my project.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
