### ISSUE TITLE
Getting a tree of all items under an item  

### ISSUE THREAD

**Issue by sw-dev1** [OneDrive/onedrive-sdk-android#21]
What is the best practice of getting the full tree of items below an item?

The documentation says  "By using these request builders you can retrieve all of the items under a collection no matter the size." But how exactly should this be done? The example is incomplete in the call to .get() within success(). 

Is there an example of a sequence of requests? What should be used to wait until the result of a request is available before issuing the next request?

**Comment by peternied** [comment]
The best way to get the full hierarchy of items within a OneDrive is to use the [Sync Changes API](https://dev.onedrive.com/items/view_delta.htm), this can be done with an `IDeltaRequest`.  To see a full example of how to retrieve a delta collection and make requests to get all pages see the OneDrive Explorer for Android's [DeltaFragment](https://github.com/OneDrive/onedrive-explorer-android/blob/master/app/src/main/java/com/microsoft/onedrive/apiexplorer/DeltaFragment.java#L126)

Here is truncated example, which would work with any result of a CollectionPage.  We create the request against the resource (the logic within `refresh()`), then for the `ICallback<*Page>` handler we use a function to generate the next handler, then within the handler if we have another page we make a recursive call to get the next page 

``` java
    private void refresh() {
        oneDriveClient
            .getDrive()
            .getRoot()
            .getDelta("deltaToken")
            .buildRequest()
            .get(pageHandler());
    }

    private ICallback<IDeltaCollectionPage> pageHandler() {
        return new ICallback<IDeltaCollectionPage>() {
            @Override
            public void success(final IDeltaCollectionPage page) {
                // Be productive with page.getCurrentPage()

                // Handle scenario with multiple pages
                if (page.getNextPage() != null) {
                    page.getNextPage()
                        .buildRequest()
                        .get(pageHandler());
                }
            }
        };
    }
```

**Comment by sw-dev1** [comment]
Thanks! Unfortunately the sample app crashes on my Windows emulator with a hierarchy of 50-60 items. 

Tracking the response down in the sample code leads to mPageContents in BaseCollectionPage. The interface IBaseCollectionPage, which BaseCollectionPage implements, involves - indirectly - a JsonObject, which in turn maintains a LinkedTreeMap of its children. Is it correct that mPageContents is a flat list representation of the tree in the JsonObject?

**Comment by peternied** [comment]
@sw-dev1 Could you create a [new issue](https://github.com/OneDrive/onedrive-explorer-android) a gist of the app crashing along with the devices logcat on the sample application?

Yes, mPageContents list representation of the item tree element in the json response, which is fully described [here](https://dev.onedrive.com/items/list.htm).

**Comment by sw-dev1** [comment]
Thanks again for the clarification.

The crash happens when testing against a live account, which would contain personal data in the logcat. I tried to reproduce the behavior with a test account having fewer items. The app does not crash but the emulator screen freezes and scrolling is not possible. Back button works though. Would you like me to create an issue with this?

**Comment by peternied** [comment]
@sw-dev1 Without a log of what is happening on the device during the crash I won't be able to address this issue.  If you can a log and you can share it to me privately or if there is an exception stack trace then I can work this issue.

**Comment by sw-dev1** [comment]
I could recreate the crash with the first account and then extracted the necessary (in my view) part of the logcat that does not contain personal data. As requested, I have then created an issue for [onedrive-explorer-android](https://github.com/OneDrive/onedrive-explorer-android):  [App crash on windows emulator at view.delta with large hierarchy](https://github.com/OneDrive/onedrive-explorer-android/issues/63). Hoping it helps.

**Comment by peternied** [comment]
I'm going to close out this issue, as it is a bug in the sample application not this SDK, thanks for filing!

**Comment by sw-dev1** [comment]
@peternied Thanks for your help so far. 
Next challenge is to use the collected list of items from the delta pages. It seems that the SDK design imposes that the complete logic for manipulating the result of all requests needs to be in the success method of the callback. In this case however, due to the recursive calls of the request from within success, this would make the success method very complex and difficult to test. 
While looking for a solution I thought AsyncMonitor would be a way  to go. However get() in IBaseDeltaRequest accepts only <IDeltaCollectionPage> and not <AsyncMonitor<>> as the template parameter. 
Would there be a similar facility in the SDK for a delta request?
If not, would wait() and notify() or something around synchronize be recommendable?
Cheers.

**Comment by sw-dev1** [comment]
@peternied Thanks for your help. 
 Next challenge is to use the collected list of items from the delta pages. It seems that the SDK design imposes that the complete logic for manipulating the result of all requests needs to be in the success method of the callback. In this case however, due to the recursive calls of the request from within success, this would make the success method very complex and difficult to test. 
 While looking for a solution I thought AsyncMonitor would be a way to go. However get() in IBaseDeltaRequest accepts only <"IDeltaCollectionPage> and not <"AsyncMonitor<"IDeltaCollectionPage>> as the template parameter. 
 Would there be a similar facility in the SDK for a delta request?
 If not, would wait() and notify() or something around "synchronize" be recommendable?
 Cheers.

**Comment by peternied** [comment]
Well you could use a `SimpleWaiter` to wait for a response without any pages and then trigger another flow that uses that information, or you could use a second layer of callbacks that aggregated list of page contents.  I'm thinking that second method would work a little better for this purposes.

You could also look to add an extension within [DeltaRequest](https://github.com/OneDrive/onedrive-sdk-android/blob/master/onedrivesdk/src/main/java/com/onedrive/sdk/extensions/DeltaRequest.java) that would let you get the kind of response you want with a pattern like the AsyncMonitor.

``` java
    // Example using an nested callback
    private void refresh() {
        final MyCallback callback= new MyCallback() {
            public final List<Item> mItems = new List<Item>();
            public void totalSuccess() { }
            public void anyFailure(...) {}
        };
        oneDriveClient
            .getDrive()
            .getRoot()
            .getDelta("deltaToken")
            .buildRequest()
            .get(pageHandler(callback));
        waiter.waitForSignal();
    }

    private ICallback<IDeltaCollectionPage> pageHandler(final MyCallback myCallback) {
        return new ICallback<IDeltaCollectionPage>() {
            @Override
            public void success(final IDeltaCollectionPage page) {
                // Be productive with page.getCurrentPage()
                myCallback.mItems.Add(page.getCurrentPage())

                // Handle scenario with multiple pages
                if (page.getNextPage() != null) {
                    page.getNextPage()
                        .buildRequest()
                        .get(pageHandler(callback));
                } else {
                    myCallback.totalSuccess();
                }
            }
        };
    }
```

**Comment by sw-dev1** [comment]
Thank you. I'll try this out.
