### ISSUE TITLE
Not Getting login Callback

### ISSUE THREAD

**Issue by ishroid** [OneDrive/onedrive-sdk-android#26]
I am not getting proper callback from onedriveclient, i have to restart app to get logged in.

i am using 

com.onedrive.sdk:onedrive-sdk-android:1.0.0

new OneDriveClient
                .Builder()
                .fromConfig(createConfig())
                .loginAndBuildClient(activity, callback);

**Comment by peternied** [comment]
Could you include the logcat output when you start to login and it seems not to finish logging in?

**Comment by ishroid** [comment]
I was using 

com.onedrive.sdk:onedrive-sdk-android:1.0.0,

after updating it to 1.0.2 , i am able to get login callback properly,

Thank you

**Comment by peternied** [comment]
@ishratkhan Glad to hear this was resolved!
