### ISSUE TITLE
Download progress and create folder

### ISSUE THREAD

**Issue by sw1ftc0d3r** [OneDrive/onedrive-sdk-android#28]
Hi,
I want to know how to get the progress of download and create an empty folder.
It's possible? 
Thanks in advance!

**Comment by daboxu** [comment]
Hi Andrea,

For creating an empty folder, you can follow the instruction at the last part in this [doc](https://github.com/OneDrive/onedrive-sdk-android/blob/master/docs/collections.md#create-a-folder) about creating an empty folder.

For showing download progress, there are two ways but  I am not sure which one could meet your needs:
    1. In the [example app](https://github.com/OneDrive/onedrive-explorer-android) we use Android's Download Manager to handle download progress, here is the [example](https://github.com/OneDrive/onedrive-explorer-android/blob/master/app/src/main/java/com/microsoft/onedrive/apiexplorer/ItemFragment.java#L844).
    2. you can also track the progress by yourself as you get the inputstream. Here is the [example](https://github.com/OneDrive/onedrive-explorer-android/blob/master/app/src/main/java/com/microsoft/onedrive/apiexplorer/DisplayItem.java#L91) shows how to get inputstream from SDK.

Dabo

**Comment by peternied** [comment]
Sounds like this should be resolved, closing out this old issue.
