### ISSUE TITLE
WebView SSL vulnerability

### ISSUE THREAD

**Issue by phileo** [OneDrive/onedrive-sdk-android#31]
https://github.com/liveservices/LiveSDK-for-Android/issues/63

Has the Live SDK issue been addressed in this project as well?

**Comment by peternied** [comment]
This project doesn't not include that terrible SSL hack.  This library is vastly more security compliant and uses the HTTP libraries as per the latest guidance from the Android documentation.

**Comment by peternied** [comment]
Let me know if this issue is not resolved, closing this out
