### ISSUE TITLE
Expand Children and thumbnails with new API?

### ISSUE THREAD

**Issue by phileo** [OneDrive/onedrive-sdk-android#32]
# In the old API, I used the following QueryOptions request to retrieve expanded collection of children with medium res thumbnails:

`children(expand=thumbnails(select=medium)),thumbnails(select=medium)`

How would I achieve the equivalent result in the new API?

`oneDriveClient
    .getDrive()
    .getRoot()
    .buildRequest()
    .expand(???)
    .get(callback);`

**Comment by peternied** [comment]
For a specific item you'd want a expand statement like "thumbnails(select=medium)", he is how it could look from your example.

``` java
oneDriveClient
   .getDrive()
   .getItem(itemId)
   .buildRequest()
   .expand("thumbnails(select=medium)")
   .get(callback);
```

I noticed that your first referenced example used a children expansion as well, you can do that with this API too, it would look like this:

``` java
oneDriveClient
   .getDrive()
   .getItem(itemId)
   .buildRequest()
   .expand("children(expand=thumbnails(select=medium))")
   .get(callback);
```

For reference, the OneDrive Explorer for Android uses nearly this behavoir, see its usage within its main [item fragment](https://github.com/OneDrive/onedrive-explorer-android/blob/master/app/src/main/java/com/microsoft/onedrive/apiexplorer/ItemFragment.java#L107).

**Comment by phileo** [comment]
Thanks for the prompt response!  I will try that out.

**Comment by peternied** [comment]
Please reopen if you are still having issues, thanks!
