### ISSUE TITLE
content_downloadUrl?

### ISSUE THREAD

**Issue by phileo** [OneDrive/onedrive-sdk-android#33]
reference:
https://dev.onedrive.com/resources/item.htm
In the old API, each Item contained a downloadable url, namely `item.content_downloadUrl` that gave me access to "@content.downloadUrl" property of an Item
Where can I get access to this in new API ?

**Comment by peternied** [comment]
You can get it by peeking into the raw object, `item.getRawObject().get("@content.downloadUrl").getAsString()`, see how we just plug it into the [download manager](https://github.com/OneDrive/onedrive-explorer-android/blob/master/app/src/main/java/com/microsoft/onedrive/apiexplorer/ItemFragment.java#L844) in the example app.

**Comment by peternied** [comment]
Note: if you do `OneDriveClient.getDrive().getItems(itemId).getContent().get()` it will return an `InputStream` to the file contents, [read more here](https://github.com/OneDrive/onedrive-sdk-android/blob/master/docs/items.md#download-a-file).

**Comment by peternied** [comment]
Please reopen if you are still having issues, thanks!
