### ISSUE TITLE
Facets not available in response

### ISSUE THREAD

**Issue by phileo** [OneDrive/onedrive-sdk-android#34]
# When I make the following request:

```
                   `oneDriveClient.getDrive()
                    .getItems(itemId)
                    .getChildren()
                    .buildRequest()
                    .select("@content.downloadUrl")
                    .expand("thumbnails")
                    .get(callback)`
```

I cannot find in the `IItemCollectionPage.getCurrentPage()` the various Facets properties like item.folder , item.file , item.image, ie. they are all null.

Is this by design, or is there a way to retrieve file/folder/image facets for an Item?

**Comment by phileo** [comment]
Ok, figured out the answer:

`oneDriveClient.getDrive() .getItems(itemId) .getChildren() .buildRequest() .select("id,createdDateTime,image,folder,file,name,size,@content.downloadUrl") .expand("thumbnails") .get(callback)`

**Comment by peternied** [comment]
Yup, that would be a way to get only the facets your application is interested in

**Comment by peternied** [comment]
Please reopen if you are still having issues, thanks!
