### ISSUE TITLE
Get Profile Information

### ISSUE THREAD

**Issue by sw1ftc0d3r** [OneDrive/onedrive-sdk-android#35]
Hi! 
I want gt Profile information like email, id, ecc.
It's possible?
Thanks in advance

**Comment by peternied** [comment]
OneDrive does not have an API that provides this information, but we are tracking this kind of request on [UserVoice](https://onedrive.uservoice.com/forums/262982-onedrive/suggestions/7475062-support-retrieving-user-profile-information-via-ap),  every vote counts.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
