### ISSUE TITLE
OneDrive Authentication Cancellation issue

### ISSUE THREAD

**Issue by phileo** [OneDrive/onedrive-sdk-android#41]
After logging in with username / password, If I press no during the authentication page that asks for permissions, I get:

ClientException.mErrorCode = "AuthenticationFailure"
ClientException.cause = "com.microsoft.services.msa.LiveAuthException: The user has denied access to the scope requested by the client application."

If I press "back" while on that permissions page, I get:
ClientException.mErrorCode = "AuthenticationFailure"
ClientException.cause = "com.microsoft.services.msa.LiveAuthException: The user cancelled the login operation."

When pressing back on the permissions page, ClientException.mErrorCode should be "AuthenticationCancelled", and not "AuthenticationFailure"

**Comment by peternied** [comment]
That message comes from the OAuth service and not from the client, so we risk the message changing on us if we depend on the string.
