### ISSUE TITLE
parentReference.path is null for all items in a delta response

### ISSUE THREAD

**Issue by sw-dev1** [OneDrive/onedrive-sdk-android#42]
The items in the getDelta() response have null as their parentReference.path whereas the same items when retrieved with getItems() have the correct path. The expansion options are the same for both requests.

What is the proper way of getting the full parentReference object in the getDelta() response?

**Comment by peternied** [comment]
The proper way is to use `parentReference.id` in place of the item path.  'Random path' composition is expensive for the OneDrive service to look up, if you have an id the service will always provider a faster response since the translation layer is not needed.

**Comment by sw-dev1** [comment]
Thanks for the prompt response. 
I am aware of the importance of using the id. I store the OD id locally and work only with it as a rule. However in the first pass the local items do not have the server id yet. The most straightforward way then seems to be to compare by name and parent path. If the pair matches, the server id is set locally for later use.
Is there another way of getting the full path from the delta request?

**Comment by peternied** [comment]
When you upload the item via the OneDrive API you get an id back for the item, I would be hard pressed to come up with a reliable way to match up the local items and the remote items if you use another process.

For the Delta API returning parent paths is blocked because of the high call volume and response performance requirements.

**Comment by sw-dev1** [comment]
Thanks. I understand the constraint of the delta. Will look for another way of solving the problem.
