### ISSUE TITLE
Lower SDK version to 10?

### ISSUE THREAD

**Issue by QuickBrownFoxy** [OneDrive/onedrive-sdk-android#5]
I am using LiveSDK for Android at the moment and I'd like to move on to OneDrive SDK but it has minimum SDK 15, all my apps are minimum SDK 10. Are there any plans to lower the SDK version? At least to 10?

**Comment by peternied** [comment]
The core SDK does not have any requirements that prevent it from functioning on SDK 10, however the default authentication provides that this library depends on have min versions set at 14.
- I've already opened a pull request on the MSA Library https://github.com/MSOpenTech/msa-auth-for-android/pull/23 to lower the version number.
- It doesn't appear that the ADAL library I use had a hard requirement on SDK 14, I've opened https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/454 to follow that issue.

**Comment by peternied** [comment]
Abandoning this pull request for the time being, if there is renewed interest we can investigate this issue further.
