### ISSUE TITLE
Strange difference between SDK and code integration

### ISSUE THREAD

**Issue by isabsent** [OneDrive/onedrive-sdk-android#54]
I have faced with strange difference in the behavior of the same project trying to connect to OneDrive (not a Business) in two cases:
1. onedrive-sdk-android 1.1.3 is used as dependency [LearnAndroid_Async.zip](https://github.com/OneDrive/onedrive-explorer-android/files/142184/LearnAndroid_Async.zip)
2. source code of onedrive-sdk-android (current master version on Github) is integrated to the project [LearnAndroid_Code.zip](https://github.com/OneDrive/onedrive-explorer-android/files/142191/LearnAndroid_Code.zip)

The difference is in two details:
a) This [failure_dialog](https://cloud.githubusercontent.com/assets/4918293/13246697/65ef16ac-da3f-11e5-9c29-b1ba2d1bfd75.png) never appears when sdk is used as a dependency (case 1) and appears always in case 2.
b) After pressing "Yes" on this [access screen](https://cloud.githubusercontent.com/assets/4918293/13249582/521b9f82-da4f-11e5-8fab-7087fb42437e.png) I never seen token string on app [screen - token absense](https://cloud.githubusercontent.com/assets/4918293/13248176/32bc8d20-da47-11e5-9c0a-ed4ef1b82420.png) in the case 2 and always seen it in the case 1 - [screen - token presense](https://cloud.githubusercontent.com/assets/4918293/13248399/3fb8f10c-da48-11e5-98c8-2302f5d4dac5.png). I always have to press "LinkOneDrive" button again to view token string on app screen in the case 2.

**Which additional settings (in build.gradle?) are necessary to get the same SDK behaviour in both cases?**

P.S. I have no access to Business Cloud now and I can't check, but it seems I had not such a difference with Business Cloud earlier.

**Comment by peternied** [comment]
Gradle dependency is the supported method of using this library.  This issue is rather old at this point, please reopen if this is still a problem.
