### ISSUE TITLE
Replacing Okhttp with Volley

### ISSUE THREAD

**Issue by eicm** [OneDrive/onedrive-sdk-android#55]
Is it possible to replace okHttp library with Volley inside the SDK?

**Comment by peternied** [comment]
Yes, the majors pieces of the SDK are built along interfaces that are [wholly replaceable](https://github.com/OneDrive/onedrive-sdk-android/blob/master/docs/extensibility.md#major-dependencies).  If you would like to use an different http provider, you just need a new [`IHttpProvider`](https://github.com/OneDrive/onedrive-sdk-android/blob/master/onedrivesdk/src/main/java/com/onedrive/sdk/http/IHttpProvider.java) implementation that uses okHttp.

We do not have any plans to build any alternative IHttpProvider for this SDK, but we would be happy to review a pull request to add new HttpProviders.

**Comment by peternied** [comment]
We will not be looking to take new dependencies onto this core library such as OkHttp or Volley.
