### ISSUE TITLE
Needs synchronous API

### ISSUE THREAD

**Issue by 1gravity** [OneDrive/onedrive-sdk-android#57]
Integrating with different cloud storage providers is best done by implementing a wrapper around the different provider's APIs. DropBox and Google Drive both have an synchronous API for accessing the actual drive while OneDrive's API is mostly asynchronous. A wrapper obviously needs to be asynchronous or it would block the ui thread. When asynchronous API meets another asynchronous API it get's either really complicated or one needs to make the asynchronous calls to OneDrive synchronous/blocking (which I did). It would be convenient if OneDrive had a synchronous API too.

I'm aware that changing the API with all it's callback isn't easy and it's actually not necessary. It would be sufficient to offer a mechanism to use blocking calls by using something like this: http://stackoverflow.com/a/35989208/534471.

**Comment by peternied** [comment]
This SDK exposes synchronous and asynchronous methods for nearly all functionality, for example you can use the following techniques to get access to a drive.  Does this meet your requirements?

``` java
// Asynchronous
client
   .getDrive()
   .buildRequest()
   .get(new ICallback<Drive>() {
      @Override
      public void success(final Drive result) {
         final String msg = "Found Drive " + result.id;
         Toast.makeText(getActivity(), msg, Toast.LENGTH_SHORT).show();
      }

      @Override
      public void failure(final ClientException ex) {
         // Handle failure case
      }
);
```

``` java
// Synchronous
try {
   final Drive result = client
                          .getDrive()
                          .buildRequest()
                          .get();
   final String msg = "Found Drive " + result.id;
   Toast.makeText(getActivity(), msg, Toast.LENGTH_SHORT).show();
} catch (final ClientException ex) {
   // Handle failure case
}
```

If you are looking for additional control over the execution model there is a [IExecutors interface](https://github.com/OneDrive/onedrive-sdk-android/blob/master/onedrivesdk/src/main/java/com/onedrive/sdk/concurrency/IExecutors.java#L30) which can be used to control execution of foreground vs background tasks.

**Comment by 1gravity** [comment]
This is indeed what I was looking for. Sorry my bad ;-)
