### ISSUE TITLE
Check permissions

### ISSUE THREAD

**Issue by 1gravity** [OneDrive/onedrive-sdk-android#58]
Can your library check the permissions it needs to run and throw an exception if the permissions aren't granted?
I just spent a lot of time because one of my Gradle flavors had
`<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" tools:node="remove"/>`
in its manifest and I didn't remember any more (that's my fault of course).
As a consequence the token could not be refreshed and the app simply stopped doing anything (log output stopped when it says it's going to refresh the token).

You can check the permissions using this e.g.:
http://developer.android.com/reference/android/support/v4/content/ContextCompat.html#checkSelfPermission(android.content.Context, java.lang.String)

Thank you!

**Comment by peternied** [comment]
We would be happy to accept a pull request that handles this kind of permissions check, if you'd like an example of an existing permission check [this class](https://github.com/OneDrive/onedrive-sdk-android/blob/master/onedrivesdk/src/main/java/com/onedrive/sdk/authentication/adal/BrokerPermissionsChecker.java) would serve a great starting point

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
