### ISSUE TITLE
Get rid of accounts permissions

### ISSUE THREAD

**Issue by 1gravity** [OneDrive/onedrive-sdk-android#59]
Why does the SDK need all the accounts permissions? I understand that the Google Drive SDK asks for that permission since it's using the device's accounts for identification to the drive but OneDrive should not need it because the user already provides the credentials to authenticate.

On Android this gets worse because it's all under the Contacts permission. I can't explain to the users why my app needs access to their contacts simply because they want to save some files on OneDrive...

**Comment by peternied** [comment]
Those permissions are required for the Azure Active Directory library [ADAL](https://github.com/AzureAD/azure-activedirectory-library-for-android). If you are not using the ADAL library dependency  `compile 'com.microsoft.aad:adal:X.X.X'`, you can use the [manifest merger](http://tools.android.com/tech-docs/new-build-system/user-guide/manifest-merger#TOC-Element-Removal) to remove these permission nodes from your application.

Here is the manifest changes you could add to your application to remove an inherit permissions around account management.

``` xml
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools" <!-- Make sure you include the tools namespace -->
    package="com.application.package">

    <uses-permission android:name="android.permission.GET_ACCOUNTS" tools:node="remove"/>
    <uses-permission android:name="android.permission.USE_CREDENTIALS" tools:node="remove"/>
    <uses-permission android:name="android.permission.MANAGE_ACCOUNTS" tools:node="remove"/>
```

We are reviewing the relationship between authentication and the OneDrive SDK, stay tuned.

**Comment by 1gravity** [comment]
This answer isn't correct.
Even if com.microsoft.aad:adal:1.1.11 isn't used (only com.microsoft.services.msa:msa-auth:0.8.4) the SDK still wants the permission.
My understanding is that the ADAL is needed for OneDrive for Business although I can access the OneDrive for Business by using the msa-auth library only for both MSA and ADAL authentication, so not sure why the ADAL even exists.
Anyway "permissions are required for the Azure Active Directory" isn't an explanation I can give to my users but then I guess you guys are too detached from the user front to give this the right priority. If you get contacted by users on a daily basis or get bad reviews because of excessive permissions you'd feel the pain and so I'd ask you to re-open the issue (it's simply not solved).

**Comment by alexeyvasilyev** [comment]
I completely agree. It is not clear why these permissions needed.

I use Dropbox SDK, Amazon Drive SDK, Google Drive SDK, and MS Live SDK (obsolete) as well, and none of them adds silently permissions in AndroidManifiest.xml. Why OneDrive SDK needs them?

You should put a warning on your home page regarding that.

This issue should be reopened and fixed. There is no reason for such dangerous permissions in SDK. If you need these permissions for OneDrive for Business, then create another small library with these permissions and additional OneDrive for Business logic.
