### ISSUE TITLE
Access to extended visibility flags denied: Requires com.sonymobile.permission.SYSTEM_UI_VISIBILITY_EXTENSIONS permission

### ISSUE THREAD

**Issue by 1gravity** [OneDrive/onedrive-sdk-android#60]
On certain Sony devices, when the authentication screen tries to open (webview), it shows a blank page and nothing happens afterwards. Logcat shows the following error:

> Access to extended visibility flags denied: Requires com.sonymobile.permission.SYSTEM_UI_VISIBILITY_EXTENSIONS permission

When I add the permission to the manifest, everything is back to normal:
`
<uses-permission android:name="com.sony.mobile.permission.SYSTEM_UI_VISIBILITY_EXTENSION" />
`

This happens on a Sony Xperia Z, maybe other Sony devices are affected too.
Since some developers will likely not test on a Sony device, the fix for this should be to not use whatever is specific to that login screen (other webviews like the Dropbox authentication work perfectly so there must be something specific to the OneDrive SDK implementation).
I'm using these libraries:

```
    compile('com.onedrive.sdk:onedrive-sdk-android:1.1.3')
    compile 'com.google.code.gson:gson:2.6.2'
    compile 'com.microsoft.services.msa:msa-auth:0.8.4'
```

**Comment by peternied** [comment]
@1gravity Thanks for the report. Do you know much about the `com.sony.mobile.permission.SYSTEM_UI_VISIBILITY_EXTENSION` permission? I looked around and didn't see any documentation on what it does/doesn't for those devices, do you have more details on the device or why it might require such permissions?

**Comment by 1gravity** [comment]
I didnt' find much either. Here's a start:
https://developer.sony.com/?s=com.sony.mobile.permission.SYSTEM_UI_VISIBILITY_EX
My experience with Sony is that they have no developer support whatsoever, no documentation, nothing. Sorry can't be of much help here. My guess is it has something to do with the window features
(as in activity.requestWindowFeature(Window.FEATURE_NO_TITLE) etc.).

**Comment by peternied** [comment]
@1gravity Could you try upgrading your MSA-Auth-for-Android library to version 0.8.6 and see if this fixes the permissions issue?  If you are still having problems please reopen

**Comment by 1gravity** [comment]
Yes it's fixed.
Thanks for being so responsive.
