### ISSUE TITLE
Dependencies exclusion for module is not correct

### ISSUE THREAD

**Issue by peternied** [OneDrive/onedrive-sdk-android#64]
Originally asked by @1gravity 

The build.gradle defines the dependencies like this:

```
dependencies {
    compile ('com.microsoft.services.msa:msa-auth:0.8.4') {
        exclude module: 'com.microsoft.services.msa'
    }
    compile ('com.microsoft.aad:adal:1.1.7') {
        exclude module: 'com.microsoft.aad'
    }
    compile ('com.google.code.gson:gson:2.3.1') {
        exclude module: 'com.google.code.gson'
    }
}
```

My guess is that you want to exclude the adal and msa libraries from the aar you're distributing which makes sense since not everyone would want both authentication methods. That's why your readme says to set up the dependencies like this:

```
dependency {
    compile 'com.onedrive.sdk:onedrive-sdk-android:1.1+'
    compile 'com.google.code.gson:gson:2.3.1'
    compile 'com.microsoft.services.msa:msa-auth:0.8.4'
    compile 'com.microsoft.aad:adal:1.1.11'
}
```

Unfortunately the excludes don't work and I get the following for the dependencies:
+--- com.onedrive.sdk:onedrive-sdk-android:1.1.3
|    +--- com.microsoft.aad:adal:1.1.7
|    |    --- com.android.support:support-v4:24.0.0-alpha1
|    |         --- LOCAL: internal_impl-24.0.0-alpha1.jar
|    --- com.microsoft.services.msa:msa-auth:0.8.4

That's the reason I don't have to add any dependencies in my gradle script except the one to the sdk of course and that's why I was confused why I need the adal at all (in fact it works "without" msa library too).

Now to make this correct, please use (instead of module:...):

```
exclude group: 'com.microsoft.services.msa'
exclude group: 'com.microsoft.aad'
```

This also makes sure the user can use the latest msa and adal libraries without running into dependency issues.

**Comment by peternied** [comment]
I tried using exclude group and locally still see the ADAL module imported, I'm doing a little more background research into how this should be resolved and how I can verify. As might just change the guidance to use `transitive = false`;

**Comment by 1gravity** [comment]
I have this in my Gradle script:

```
    compile ("com.onedrive.sdk:onedrive-sdk-android:1.1.3") {
        exclude group: 'com.microsoft.services.msa'
        exclude group: 'com.microsoft.aad'
        exclude group: 'com.google.code.gson'
        exclude group: 'com.android.support'
    }
```

Without adding the needed library dependencies, it will only compile and deploy my app with the sdk but the app then crashes with a java.lang.NoClassDefFoundError: Failed resolution of: Lcom/microsoft/services/msa/LiveAuthClient.

The same when I just add the @aar:

```
compile ("com.onedrive.sdk:onedrive-sdk-android:1.1.3@aar")
```

Or when I use transitive = false:

```
compile ("com.onedrive.sdk:onedrive-sdk-android:1.1.3") {
        transitive = false;
}
```

Once I add this to the dependencies everything is back to normal:

```
    compile "com.microsoft.services.msa:msa-auth:0.8.6"
    compile "com.microsoft.aad:adal:1.1.16"
    compile "com.google.code.gson:gson:2.6.2"
```

I don't recommend the @aar version because that means the pom file is ignored and that could have unintended side effects. The transitive = false is probably the cleanest solution.
