### ISSUE TITLE
ExceptionInInitializerError at LiveAuthClient.loginSilent

### ISSUE THREAD

**Issue by sw-dev1** [OneDrive/onedrive-sdk-android#68]
App with SDK crashes on a device at first start (new install).  Gist: https://gist.github.com/sw-dev1/66e22e5d5db95cf090c34ee1d8c0d24d

**Comment by peternied** [comment]
Since the loginAndBuildClient() call will invoke UI this needs to be done from a UI thread, or a thread that has called Looper.Prepare().

You can see some common techinques to handle this kind of operation from the [Android documentation on WorkerThreads](http://developer.android.com/guide/components/processes-and-threads.html#WorkerThreads).

**Comment by sw-dev1** [comment]
Thanks! But I thought I had ensured no other thread than the UI calls loginAndBuildClient() in this way (similar to the explorer sample):
in the BaseApplication:
...
    public synchronized IOneDriveClient getOneDriveClient() {
         if (mClient.get() == null) {
             throw new UnsupportedOperationException("Service object not available");
        }
        return mClient.get();
    }

...
in MainActivity (the UI thread):
...
    try {
            mApplication.getOneDriveClient();
        } catch (final UnsupportedOperationException ignored) {
            mApplication.createOneDriveClient(this, serviceCreated);
        }
...
Only createOneDriveClient() calls loginAndBuildClient() an that in turn is called only in the MainActivity. All other threads that call getOneDriveClient() catch the UnsupportedOperationException and do their own handling, none of which occurred. 

Could there be another reason why Looper.Prepare() was not called?

**Comment by peternied** [comment]
I'm not sure of why you are seeing that behavior, if you had a reproduction of the failure on a fork of the OneDrive-Explorer-Android we could take a quick look,

Since this issue is rather old, please reopen if this is still a problem
