### ISSUE TITLE
MSA Authenticator asks repeatedly for permission

### ISSUE THREAD

**Issue by 1gravity** [OneDrive/onedrive-sdk-android#69]
This is related to https://github.com/OneDrive/onedrive-sdk-android/issues/36.

While issue 36 is solved (OneDrive 4 Business), the same or similar issue exists with the regular OneDrive (MSA).
- Authenticate using a OneDrive account (non business, ui) + grant permissions
- Swipe the app from the recent list (-> app is killed)
- Re-open the app, app tries to login again -> the user gets the popup asking for permission (which was already granted). This happens each time, also when the device is restarted.

I'm using the unaltered latest versions of all libraries:

```
    compile ("com.onedrive.sdk:onedrive-sdk-android:1.1.4") {
        transitive = false;
    }
    compile "com.microsoft.services.msa:msa-auth:0.8.6"
    compile "com.microsoft.aad:adal:1.1.16"
    compile "com.google.code.gson:gson:2.6.2"
```

I compared this to the explorer sample app and here's the difference: the scope. The sample app requests "wl.offline_access" which my app doesn't. If I add that scope all works as expected.
My device isn't offline so this permission should not be needed.

https://dev.onedrive.com/auth/msa_oauth.htm:

> Allows your application to receive a refresh token so it can work offline even when the user isn't active

**Comment by peternied** [comment]
Sorry for the delay, I was out of the office.

If you do not have the `wl.offline_access` scope in your application, the user will be prompted to authorize your application via OAuth flow ever time they start the application.  If you want the login, and not be prompted again experience for your users you will need to add that scope.

**Comment by peternied** [comment]
Closing out this older issue, please reopen if this is still a problem
