### ISSUE TITLE
OneDrive for Business: "MoveFile" doesn't throw client exception if file already exists

### ISSUE THREAD

**Issue by ThomasSHA** [OneDrive/onedrive-sdk-android#70]
I implemented a "move" -fileoperation 
So I used `...buildRequest().patch(newLocation, new ICallback<Item(){....}`

When using MSA i get a `failure` callback with an `OneDriveErrorCodes.NameAlreadyExists`-Error
This is great. 

When using OneDrive for Business Account, it just successfully finishes, which is not really I would expect ;)

I hope you can help me again

Thanks in advance,
Thomas

**Comment by ThomasSHA** [comment]
Another related question:
Would it be possible to get an `NameAlreadyExists`-Error also when `post`ing a new item (in my case a folder) and copying (`getCopy(...).buildRequest().post()`)?

Or is there a way to easily get information if a "name" already exists in a folder, rather then iterating over the folder's children?
edit: ok I maybe found a "nicer" way: `mOneDriveClient.getDrive().getItems(folder).getChildren(itemName).buildRequest().get();`
but although I catch the ClientException I get the whole error in logcat. Is it possible to remove this log output (It seems to come from DefaultHttpProvider line 202  ( `this.mLogger.logError("OneDrive Service exception "` ). Maybe you could introduce some kind of new logging lvl which does not log such things :)

**Comment by ThomasSHA** [comment]
`mOneDriveClient.getDrive().getItems(folder).getChildren(itemName).buildRequest().get();`
doesn't seem to work with OneDrive for Business =>        `com.onedrive.sdk.http.OneDriveServiceException: Error code: Unable to parse error response message`

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
