### ISSUE TITLE
Error during HTTP request caused by UnknownHostException: Unable to resolve host

### ISSUE THREAD

**Issue by sw-dev1** [OneDrive/onedrive-sdk-android#72]
Logcat: https://gist.github.com/sw-dev1/1c22501730731fb45da5fc4f82b75a3f

Is this a permanent or temporary error? What code from OneDriveErrorCodes is thrown in this case?What would be the suggested action when catching this error?

**Comment by peternied** [comment]
It looks like the URL returned from the OneDrive service did not actually map an entry in the OneDrive's DNS.  Does this error persist with this item or other items as well if you get a fresh download url?  Could you include more details from the logcat output where you lookup the item information, did you attempt to download from https://api.onedrive.com/drive/items/{item-id}/content or follow the @content.downloadUrl link?

**Comment by sw-dev1** [comment]
I used https://api.onedrive.com/v1.0/drive/items/2A37E14FEF9805AF!53113/content, which failed with host 8ggnvq.bn1303.livefilestore.com, as in the linked Gist. I saw this with two more items:
2A37E14FEF9805AF!53287/content, which failed with missing host 8mghvq.bn1303.livefilestore.com. The other occurrence was for 2A37E14FEF9805AF!53130, failing with the same host

The errors were happening at a certain time of the day for about 10-15 minutes, then I stopped testing. I can't say if it persisted because I did not repeat the request for the same item(s).

Would you suggest to repeat the request as a workaround? Is there a specific code to look for from OneDriveErrorCodes for identifying this case?

**Comment by peternied** [comment]
For a network issue like this, your application should prompt the user to retry/refresh, or have a dynamic back-off algorithm, like if failure wait X, then retry, X=X^2 for future attempts.

This is an unexpected error within the OneDrive service, I'm digging into it now.  I'll circle back when I have more information for you.

If you do encounter this issue again could you please upload a new GIST

**Comment by peternied** [comment]
Wrong button.

**Comment by peternied** [comment]
I've looked into this issue and have been unable to see any errors with the service that would be associated with this kind of failure.  If you encounter this issue again please reopen or create a new issue.
