### ISSUE TITLE
Restore OneDrive session with existing access token

### ISSUE THREAD

**Issue by OlegRy** [OneDrive/onedrive-sdk-android#73]
Is there any way to restore session in OneDrive if I have an access token which was received earlier (e.g. I authorized in OneDrive on another device and got access token and then I need restore session with the same token)?

**Comment by peternied** [comment]
When requesting scopes by adding the `wl.offline_access` scope the authentication response will include a refresh token which can be used to acquire a new access token without a interactive login flow.

If you use the MSAAuthenticator, this will automatically store/manage/use this refresh token.  To see a full application example that uses the offline access scope of scenario see, the [OneDrive Explorer for Android](https://github.com/OneDrive/onedrive-explorer-android), and look here for the  [MSAAuthenticator configuration](https://github.com/OneDrive/onedrive-explorer-android/blob/master/app/src/main/java/com/microsoft/onedrive/apiexplorer/BaseApplication.java#L86).

**Comment by peternied** [comment]
Closing out this issue, please reopen this is still a problem.
