### ISSUE TITLE
Couldn't get required info after having followed the setup steps

### ISSUE THREAD

**Issue by diogowbrito** [OneDrive/onedrive-sdk-android#75]
After following the link posted on README (https://dev.onedrive.com/app-registration.htm) and setting up a new account and a new OneDrive app I wasn't able to get the `msa-client-id` id, I was only able to fetch the `adal-client-id` id.

This is what my app page looks like. Is the README up to date? Do I require both keys?
<img width="1197" alt="screen shot 2016-05-12 at 18 55 58" src="https://cloud.githubusercontent.com/assets/739100/15224786/30aa5728-1873-11e6-99ed-8cb740d9cdcb.png">

**Comment by daboxu** [comment]
hi @diogowbrito , this portal is supposed to provide new version Microsoft Account experience. The app registered on the portal should work fine with the [Microsoft Graph Android SDK](https://github.com/microsoftgraph/msgraph-sdk-android). You should use the [MSA Auth Adapter for Microsoft Graph](https://github.com/microsoftgraph/msgraph-sdk-android-msa-auth-for-android-adapter).
