### ISSUE TITLE
Sometimes upload doesn't work when upload a file to OneDrive for Business

### ISSUE THREAD

**Issue by yanbli** [OneDrive/onedrive-sdk-android#76]
I find it can work one day, but next day it doesn't work.

the call stack is:

13881-14190/? D/DefaultHttpProvider[sendRequestInternal] - 244: Response code 503, Service Unavailable
05-19 02:49:07.468 13881-14190/? D/DefaultHttpProvider[sendRequestInternal] - 249: Handling error response
05-19 02:49:07.475 13881-14190/? E/DefaultHttpProvider[sendRequestInternal] - 305: OneDrive Service exception Error code: Unable to parse error response message
                                                                                   Error message: Raw error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html><head>    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">    <meta http-equiv="X-UA-Compatible" content="IE=10" />    <title id="SharePoint Online">Something's not right</title>    <style>        #ms-error-body {            background-size: auto;            overflow: auto;            width: 830px;            margin-right: auto;            margin-left: auto;        }        html > .ms-core-needIEFilter {            -ms-filter: "progid:DXImageTransform.Microsoft.AlphaImageLoader(src='about:blank',sizingMethod='scale');";        }        body {            margin: 0px;            overflow: hidden;            background-color: #fff;            background-size: cover;            background-repeat: no-repeat;        }        body, .ms-core-defaultFont, #pageStatusBar, .ms-status-msg, .js-callout-body {            font-family: "Segoe UI","Segoe",Tahoma,Helvetica,Arial,sans-serif;            font-size: 13px;        }        #ms-error-header {            margin: 118px 0px 16px;            min-height: 50px;        }        .ms-core-pageTitle {            font-size: 2.77em;            white-space: nowrap;        }        .ms-core-pageTitle, .ms-core-pageTitle a {            font-family: "Segoe UI Light","Segoe UI","Segoe",Tahoma,Helvetica,Arial,sans-serif;            color: #262626;        }        h1, .ms-h1 {            font-family: "Segoe UI Light","Segoe UI","Segoe",Tahoma,Helvetica,Arial,sans-serif;            font-size: 2.3em;            color: #777;            font-weight: 200;        }        h1, h2, h3, h4, h5, h6, .ms-h1, .ms-h2, .ms-h3, .ms-h4, .ms-h5, .ms-h6 {            margin: auto;            font-weight: normal;        }        body, .ms-core-defaultFont, .js-callout-body {            color: #444;        }    </style></head><body class="ms-core-needIEFilter" id="ms-error-body">    <div class="ms-pr" id="ms-error-header">        <h1 class="ms-core-pageTitle" id="errortitle">Something's not right</h1>        <p id="errortext">The page you requested is temporarily unavailable. We apologize for the inconvenience, please check back in a few minutes.</p>    </div><div id='errorref'><span>Ref A: E4BCD333649A4FC988B9D1C6ABC3BF4D Ref B: FCE6C34DEF377C1F9F416425DF78F909 Ref C: Wed May 18 23:49:06 2016 PST</span></div></div></body></html>
05-19 02:49:07.476

**Comment by yanbli** [comment]
I also try the onedrive-explorer sample. It has the same issue.

**Comment by yanbli** [comment]
@daboxu What's the root cause about this issue? It happens again today. Per two days, it will happen.

**Comment by daboxu** [comment]
#80

**Comment by daboxu** [comment]
#80 should have fixed this.

**Comment by daboxu** [comment]
@yanbli can you confirm the issue has gone?

**Comment by yanbli** [comment]
@daboxu  in sdk 1.2.1 the previous issues is gone. But new issue happen. Do I need to encode the path? I find if don't encode the path for onedrive personal, it can work. But it doesn't work for onedrive business no matter encode the path

**Comment by daboxu** [comment]
gone with fix #82
