### ISSUE TITLE
Use as a file server

### ISSUE THREAD

**Issue by Hamix** [OneDrive/onedrive-sdk-android#78]
Hi
I want to use my 'onedrive' as a file server and share my drive files for other user. is it possible?
I do not know exactly what is the purpose of "MSA authentication ClientId" 
I have read this link [register-your-app](https://dev.onedrive.com/auth/msa_oauth.htm#to-register-your-app)
I created a new password in "Application Secrets" part and wrote this code

```
private IClientConfig createConfig() {
         final ADALAuthenticator adalAuthenticator = new ADALAuthenticator() {
            @Override
            public String getClientId() {
                return "00000000-0000-0000-0000-000000000000";
            }

            @Override
            protected String getRedirectUrl() {
                return "urn:ietf:wg:oauth:2.0:oob";
            }
        };
        final MSAAuthenticator msaAuthenticator = new MSAAuthenticator() {
            @Override
            public String getClientId() {
                return "my app password";
            }

            @Override
            public String[] getScopes() {
                return new String[] {"onedrive.readwrite", "onedrive.appfolder", "wl.offline_access"};
            }
        };

        final IClientConfig config = DefaultClientConfig.createWithAuthenticators(msaAuthenticator,adalAuthenticator);
        config.getLogger().setLoggingLevel(LoggerLevel.Debug);
        return config;
    }

```

```
synchronized void createOneDriveClient(final Activity activity) {        
        new OneDriveClient
            .Builder()
            .fromConfig(createConfig())
            .loginAndBuildClient(activity);
    }
```

here is my logcat

> 05-21 02:01:16.589 30085-30085/com.hashsoft.myapp I/BaseApplication[createConfig] - 111: Setting logging level to Debug
> 05-21 02:01:16.591 30085-30085/com.hashsoft.myapp D/DefaultClientConfig[getExecutors] - 148: Created DefaultExecutors
> 05-21 02:01:16.628 30085-30085/com.hashsoft.myapp D/DefaultClientConfig[getSerializer] - 135: Created DefaultSerializer
> 05-21 02:01:16.630 30085-30085/com.hashsoft.myapp D/DefaultClientConfig[getHttpProvider] - 122: Created DefaultHttpProvider
> 05-21 02:01:16.631 30085-30085/com.hashsoft.myapp D/DisambiguationAuthenticator[init] - 128: Initializing MSA and ADAL authenticators
> 05-21 02:01:16.647 30085-30085/com.hashsoft.myapp V/PRNGFixes: 2016-05-20 21:31:16-null-No need to apply the fix ver:1.1.19
> 05-21 02:01:16.648 30085-30085/com.hashsoft.myapp V/PRNGFixes: 2016-05-20 21:31:16-null-No need to apply the fix ver:1.1.19
> 05-21 02:01:16.658 30085-30085/com.hashsoft.myapp V/DefaultTokenCacheStore: 2016-05-20 21:31:16-null-Started to initialize storage helper ver:1.1.19
> 05-21 02:01:16.663 30085-30085/com.hashsoft.myapp V/DefaultTokenCacheStore: 2016-05-20 21:31:16-null-Finished to initialize storage helper ver:1.1.19
> 05-21 02:01:16.670 30085-30085/com.hashsoft.myapp V/StorageHelper: 2016-05-20 21:31:16-null-Key entry is available ver:1.1.19
> 05-21 02:01:16.671 30085-30085/com.hashsoft.myapp V/StorageHelper: 2016-05-20 21:31:16-null-Reading Key entry ver:1.1.19
> 05-21 02:01:16.687 30085-30085/com.hashsoft.myapp V/StorageHelper: 2016-05-20 21:31:16-null-Retrived keypair from androidKeyStore ver:1.1.19
> 05-21 02:01:16.689 30085-30085/com.hashsoft.myapp V/StorageHelper: 2016-05-20 21:31:16-null-Reading SecretKey ver:1.1.19
> 05-21 02:01:16.690 30085-30085/com.hashsoft.myapp V/StorageHelper: 2016-05-20 21:31:16-null-Reading key data from a file ver:1.1.19
> 05-21 02:01:16.844 30085-30085/com.hashsoft.myapp V/StorageHelper: 2016-05-20 21:31:16-null-Finished reading SecretKey ver:1.1.19
> 05-21 02:01:16.863 30085-30085/com.hashsoft.myapp D/DisambiguationAuthenticator[loginSilent] - 272: Starting login silent
> 05-21 02:01:16.866 30085-30085/com.hashsoft.myapp D/DisambiguationAuthenticator[loginSilent] - 279: Checking MSA
> 05-21 02:01:16.868 30085-30085/com.hashsoft.myapp D/MSAAuthenticator[loginSilent] - 294: Starting login silent
> 05-21 02:01:16.877 30085-30085/com.hashsoft.myapp D/MSAAuthenticator[loginSilent] - 336: MSA silent auth fast-failed
> 05-21 02:01:16.878 30085-30837/com.hashsoft.myapp I/LiveAuthClient: No refresh token available, sorry!
> 05-21 02:01:16.878 30085-30837/com.hashsoft.myapp I/LiveAuthClient: All tokens expired, you need to call login() to initiate interactive logon
> 05-21 02:01:16.878 30085-30085/com.hashsoft.myapp D/DisambiguationAuthenticator[loginSilent] - 288: Checking ADAL
> 05-21 02:01:16.879 30085-30085/com.hashsoft.myapp D/ADALAuthenticator[loginSilent] - 380: Starting login silent
> 05-21 02:01:16.880 30085-30085/com.hashsoft.myapp D/ADALAuthenticator[loginSilent] - 383: No login information found for silent authentication
> 05-21 02:01:16.881 30085-30085/com.hashsoft.myapp D/DisambiguationAuthenticator[login] - 171: Starting login
> 05-21 02:01:16.882 30085-30837/com.hashsoft.myapp E/MSAAuthenticator$5[onAuthComplete] - 314: **Failed silent login, interactive login required**
>                                                                                                 com.onedrive.sdk.authentication.ClientAuthenticatorException: Failed silent login, interactive login required
>                                                                                                     at com.onedrive.sdk.authentication.MSAAuthenticator$5.onAuthComplete(MSAAuthenticator.java:312)
>                                                                                                     at com.microsoft.services.msa.LiveAuthClient$3.doInBackground(LiveAuthClient.java:484)
>                                                                                                     at com.microsoft.services.msa.LiveAuthClient$3.doInBackground(LiveAuthClient.java:473)
>                                                                                                     at android.os.AsyncTask$2.call(AsyncTask.java:295)
>                                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
>                                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>                                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>                                                                                                     at java.lang.Thread.run(Thread.java:818)
> 05-21 02:01:16.882 30085-30085/com.hashsoft.myapp D/DisambiguationAuthenticator[login] - 200: Creating disambiguation ui, waiting for user to sign in
> 05-21 02:01:16.887 30085-30085/com.hashsoft.myapp I/WebViewFactory: Loading com.google.android.webview version 45.0.2454.95 (code 246109500)
> 05-21 02:01:16.963 30085-30085/com.hashsoft.myapp W/System: ClassLoader referenced unknown path: /system/app/WebViewGoogle/lib/arm
> 05-21 02:01:17.006 30085-30085/com.hashsoft.myapp I/cr.library_loader: Time to load native libraries: 4 ms (timestamps 8081-8085)
> 05-21 02:01:17.006 30085-30085/com.hashsoft.myapp I/cr.library_loader: Expected native library version number "", actual native library version number ""
> 05-21 02:01:17.037 30085-30085/com.hashsoft.myapp V/WebViewChromiumFactoryProvider: Binding Chromium to main looper Looper (main, tid 1) {fa3ad01}
> 05-21 02:01:17.037 30085-30085/com.hashsoft.myapp I/cr.library_loader: Expected native library version number "", actual native library version number ""
> 05-21 02:01:17.038 30085-30085/com.hashsoft.myapp I/chromium: [INFO:library_loader_hooks.cc(121)] Chromium logging enabled: level = 0, default verbosity = 0
> 05-21 02:01:17.053 30085-30085/com.hashsoft.myapp I/cr.BrowserStartup: Initializing chromium process, singleProcess=true
> 05-21 02:01:17.054 30085-30085/com.hashsoft.myapp W/art: Attempt to remove non-JNI local reference, dumping thread
> 05-21 02:01:17.058 30085-30085/com.hashsoft.myapp E/SysUtils: ApplicationContext is null in ApplicationStatus
> 05-21 02:01:17.163 30085-30857/com.hashsoft.myapp I/AudioManagerEx: AudioManagerEx created
> 05-21 02:01:17.167 30085-30857/com.hashsoft.myapp W/cr.media: Requires BLUETOOTH permission
> 05-21 02:01:17.180 30085-30085/com.hashsoft.myapp E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
> 05-21 02:01:17.247 30085-30085/com.hashsoft.myapp W/art: Attempt to remove non-JNI local reference, dumping thread
> 05-21 02:01:17.271 30085-30085/com.hashsoft.myapp W/AwContents: onDetachedFromWindow called when already detached. Ignoring
> 05-21 02:01:17.370 30085-30085/com.hashsoft.myapp D/PhoneWindow: notifyNavigationBarColor, color=0x: ff000000, token: android.view.ViewRootImplAO$WEx@6d27b8a

When I change overload to this

```
new OneDriveClient
                .Builder()
                .fromConfig(createConfig())
                .loginAndBuildClient(activity, callback);
```

 it show me "Sign in to OneDrive" page (with email field)

When I change this overload (only adalAuthenticator)
`DefaultClientConfig.createWithAuthenticator(adalAuthenticator);`
it show me sign in dialog with email and password

Actually I want all my clients use my drive without any login pages(login direct to my account)
How can i do that? Could you guide me?
**Thank you for your help :+1:**

**Comment by daboxu** [comment]
hi @Hamix , the new app portal registered app returned GUID version APP ID. You can use the GUID one in the MSA Authenticator for getting you authorized. In you case, the code should work like:

``` Java

    private IClientConfig createConfig() {
        final MSAAuthenticator msaAuthenticator = new MSAAuthenticator() {
            @Override
            public String getClientId() {
                return "<you client id>";
            }

            @Override
            public String[] getScopes() {
                return new String[] {"onedrive.readwrite", "onedrive.appfolder", "wl.offline_access"};
            }
        };

        final IClientConfig config = DefaultClientConfig.createWithAuthenticator(msaAuthenticator);
        config.getLogger().setLoggingLevel(LoggerLevel.Debug);
        return config;
    }
```

and in createOneDriveClient method: 

``` Java
        new OneDriveClient
            .Builder()
            .fromConfig(createConfig())
            .loginAndBuildClient(activity, callback);
```

For more detail about how to integrate OneDrive SDK with your app, you can see the sample app [OneDrive Explorer Android](https://github.com/OneDrive/onedrive-explorer-android)

**Comment by daboxu** [comment]
#75

**Comment by daboxu** [comment]
close issue as not received any further question from user
