### ISSUE TITLE
Lower SDK version to 14?

### ISSUE THREAD

**Issue by isabsent** [OneDrive/onedrive-sdk-android#88]
Which of your onedrive-sdk-android dependencies needs a minimum SDK version 15? Is it possible to change it to SDK version 14 at least?

**Comment by peternied** [comment]
We will not be officially supporting API14 or lower versions of Android, if you would like your application to support these scenarios you could override the minSdkVersion via the manifest merger, see [this StackOverflow answer](http://stackoverflow.com/a/29949258) which explains how this can be done.

**Comment by isabsent** [comment]
Thanks! Did not know about this possibility!
