### ISSUE TITLE
Replacing of files

### ISSUE THREAD

**Issue by OlegRy** [OneDrive/onedrive-sdk-android#95]
Is it possible to replace file on drive? For example, I had photo on drive, which was downloaded to my app. In my app I've cropped photo and now I want upload cropped photo to drive using replacing. Is it possible to do that avoiding removing?

**Comment by peternied** [comment]
You can PUT against the content of a file, and it will replace the binary content of that file.  It will update the relevant metadata on that item such as the size, but not alter any of the OneDrive metadata such as sharing links.

``` java
final byte[] replacementBinaryContent;
final ICallback<Item> contentReplacedCallback;
client.getDrive()
      .getItems("{Item-Id}")
      .getContent()
      .buildRequest()
      .put(replacementBinaryContent, contentReplacedCallback);
```

**Comment by OlegRy** [comment]
Good! Thanks!
