### ISSUE TITLE
getNextPage() does not work, gets the same page instead

### ISSUE THREAD

**Issue by saucepwn** [OneDrive/onedrive-sdk-android#96]
When calling IItemCollectionPage, I would expect that the next page is returned, however, the current page is returned over and over again.

getNextPage() returns a correct IItemCollectionRequestBuilder, in my case, with the baseUrl: "https://api.onedrive.com/v1.0/drives('me')/special('photos')/children?$skiptoken=MjAx"

However, when I call .get() on the IItemCollectionRequestBuilder, inside BaseRequest.getRequestUrl(), the query string parameter is stripped from the URL, which causes it to make a request to the original URL: "https://api.onedrive.com/v1.0/drives('me')/special('photos')/children" and return the same first 200 elements.

Below is the call stack that points exactly where the query string is being removed (sorry for the screenshot)
![image](https://cloud.githubusercontent.com/assets/5727738/16473696/a40ef6f2-3e24-11e6-876c-6e0d393007f1.png)

It looks like the query string should not be removed.

**Comment by daboxu** [comment]
hi @saucepwn try use the updated version 1.2.2 which should have the fix

**Comment by saucepwn** [comment]
Thank you! Speficially requesting version 1.2.2 fixed the issue.

`compile ('com.onedrive.sdk:onedrive-sdk-android:1.2.2') {
        transitive = false
    }`
