### ISSUE TITLE
Can not sign in with new Client ID format

### ISSUE THREAD

**Issue by khanhdd26** [OneDrive/onedrive-sdk-android#98]
I can't get it OneDrive api works with new msa-client-id format like "00000000-0000-0000-0000-000000000000", the login webview always returns: "We're unable to complete your request".

If i replace it with "0000000000000000", it works prefectly, and show the login page.

```
        final MSAAuthenticator msaAuthenticator = new MSAAuthenticator() {
            @Override
            public String getClientId() {
                return "6731de76-14a6-49ae-97bc-6eba6914xxxx"; // Not working
                //return "000000004018xxx"; // Working fine
            }

            @Override
            public String[] getScopes() {
                return new String[]{"onedrive.readwrite"};
            }
        };
```

Can you help me with it?
Thanks.

**Comment by daboxu** [comment]
hi @khanhdd26 , have you enabled LiveSDK in the new dev portal https://apps.dev.microsoft.com? 
I got my app enabled which works for me:
![capture](https://cloud.githubusercontent.com/assets/3971919/16592223/7c02b4cc-4294-11e6-8ae5-0462ed7ece71.PNG)

**Comment by khanhdd26** [comment]
Thanks for your reply.
I have enabled that option when i create a key but it didn't work.
Anyway, a day later, i created new key and it was working this time.

**Comment by daboxu** [comment]
@khanhdd26 good to know it is solved!
